"""operational core: people projects assets locations assignments

Revision ID: b345494143eb
Revises: 0001
"""
from alembic import op
import sqlalchemy as sa


revision = 'b345494143eb'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_categories',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_category_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_asset_categories_organization_id_organizations')),
    sa.ForeignKeyConstraint(['parent_category_id'], ['asset_categories.id'], name=op.f('fk_asset_categories_parent_category_id_asset_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_categories'))
    )
    op.create_index(op.f('ix_asset_categories_archived_at'), 'asset_categories', ['archived_at'], unique=False)
    op.create_index('ix_asset_categories_org_name', 'asset_categories', ['organization_id', 'name'], unique=True)
    op.create_index(op.f('ix_asset_categories_organization_id'), 'asset_categories', ['organization_id'], unique=False)
    op.create_index('ix_asset_categories_parent', 'asset_categories', ['organization_id', 'parent_category_id'], unique=False)
    op.create_table('business_counters',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('current_value', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_business_counters_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_counters')),
    sa.UniqueConstraint('organization_id', 'entity_type', name=op.f('uq_business_counters_organization_id'))
    )
    op.create_index(op.f('ix_business_counters_organization_id'), 'business_counters', ['organization_id'], unique=False)
    op.create_table('skills',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_skills_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills'))
    )
    op.create_index('ix_skills_org_name', 'skills', ['organization_id', 'name'], unique=True)
    op.create_index(op.f('ix_skills_organization_id'), 'skills', ['organization_id'], unique=False)
    op.create_table('clients',
    sa.Column('client_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=300), nullable=True),
    sa.Column('primary_contact_name', sa.String(length=150), nullable=True),
    sa.Column('primary_contact_email', sa.String(length=320), nullable=True),
    sa.Column('primary_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('billing_email', sa.String(length=320), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_clients_created_by_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_clients_organization_id_organizations')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_clients_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients'))
    )
    op.create_index(op.f('ix_clients_archived_at'), 'clients', ['archived_at'], unique=False)
    op.create_index('ix_clients_org_number', 'clients', ['organization_id', 'client_number'], unique=True)
    op.create_index(op.f('ix_clients_organization_id'), 'clients', ['organization_id'], unique=False)
    op.create_table('employees',
    sa.Column('employee_number', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('preferred_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('secondary_phone', sa.String(length=50), nullable=True),
    sa.Column('job_title', sa.String(length=150), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'CASUAL', 'TEMPORARY', 'CONSULTANT', name='employment_type'), nullable=False),
    sa.Column('employment_status', sa.Enum('ACTIVE', 'ON_LEAVE', 'OFF_ROTATION', 'SUSPENDED', 'EXITED', name='employment_status'), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=150), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('emergency_contact_relationship', sa.String(length=100), nullable=True),
    sa.Column('supervisor_id', sa.Uuid(), nullable=True),
    sa.Column('photo_url', sa.String(length=1024), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_employees_created_by_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_employees_organization_id_organizations')),
    sa.ForeignKeyConstraint(['supervisor_id'], ['employees.id'], name=op.f('fk_employees_supervisor_id_employees')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_employees_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees'))
    )
    op.create_index(op.f('ix_employees_archived_at'), 'employees', ['archived_at'], unique=False)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=False)
    op.create_index('ix_employees_org_department', 'employees', ['organization_id', 'department'], unique=False)
    op.create_index('ix_employees_org_number', 'employees', ['organization_id', 'employee_number'], unique=True)
    op.create_index('ix_employees_org_status', 'employees', ['organization_id', 'employment_status'], unique=False)
    op.create_index('ix_employees_org_supervisor', 'employees', ['organization_id', 'supervisor_id'], unique=False)
    op.create_index(op.f('ix_employees_organization_id'), 'employees', ['organization_id'], unique=False)
    op.create_table('employee_documents',
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.Enum('CV', 'EMPLOYMENT_CONTRACT', 'DRIVERS_LICENSE', 'PASSPORT', 'WORK_PERMIT', 'TRAINING_CERTIFICATE', 'MEDICAL_CERTIFICATE', 'SAFETY_CERTIFICATE', 'OTHER', name='document_type'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('file_url', sa.String(length=1024), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('issuing_authority', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_employee_documents_created_by_id_users')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_documents_employee_id_employees')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_employee_documents_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_documents'))
    )
    op.create_index(op.f('ix_employee_documents_archived_at'), 'employee_documents', ['archived_at'], unique=False)
    op.create_index('ix_employee_documents_employee', 'employee_documents', ['organization_id', 'employee_id'], unique=False)
    op.create_index(op.f('ix_employee_documents_employee_id'), 'employee_documents', ['employee_id'], unique=False)
    op.create_index('ix_employee_documents_expiry', 'employee_documents', ['organization_id', 'expiry_date'], unique=False)
    op.create_index(op.f('ix_employee_documents_organization_id'), 'employee_documents', ['organization_id'], unique=False)
    op.create_table('employee_skills',
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('proficiency_level', sa.String(length=50), nullable=True),
    sa.Column('certification_number', sa.String(length=100), nullable=True),
    sa.Column('certification_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('verified_by_id', sa.Uuid(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_skills_employee_id_employees')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_employee_skills_organization_id_organizations')),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_employee_skills_skill_id_skills')),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], name=op.f('fk_employee_skills_verified_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_skills'))
    )
    op.create_index(op.f('ix_employee_skills_employee_id'), 'employee_skills', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_skills_organization_id'), 'employee_skills', ['organization_id'], unique=False)
    op.create_index('ix_employee_skills_skill', 'employee_skills', ['organization_id', 'skill_id'], unique=False)
    op.create_index('uq_employee_skills_employee_skill', 'employee_skills', ['organization_id', 'employee_id', 'skill_id'], unique=True)
    op.create_table('projects',
    sa.Column('project_number', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_type', sa.String(length=100), nullable=True),
    sa.Column('drilling_type', sa.String(length=100), nullable=True),
    sa.Column('contract_number', sa.String(length=100), nullable=True),
    sa.Column('project_manager_id', sa.Uuid(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('expected_end_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PLANNING', 'MOBILIZING', 'ACTIVE', 'PAUSED', 'COMPLETED', 'CLOSED', 'CANCELLED', name='project_status'), nullable=False),
    sa.Column('contract_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('target_metres', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_projects_client_id_clients')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_projects_created_by_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_projects_organization_id_organizations')),
    sa.ForeignKeyConstraint(['project_manager_id'], ['employees.id'], name=op.f('fk_projects_project_manager_id_employees')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_projects_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_archived_at'), 'projects', ['archived_at'], unique=False)
    op.create_index(op.f('ix_projects_client_id'), 'projects', ['client_id'], unique=False)
    op.create_index('ix_projects_org_client', 'projects', ['organization_id', 'client_id'], unique=False)
    op.create_index('ix_projects_org_manager', 'projects', ['organization_id', 'project_manager_id'], unique=False)
    op.create_index('ix_projects_org_number', 'projects', ['organization_id', 'project_number'], unique=True)
    op.create_index('ix_projects_org_status', 'projects', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_table('locations',
    sa.Column('location_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location_type', sa.Enum('HEAD_OFFICE', 'WORKSHOP', 'WAREHOUSE', 'PROJECT_SITE', 'YARD', 'FUEL_STORAGE', 'OTHER', name='location_type'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('county_or_region', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_locations_organization_id_organizations')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_locations_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations'))
    )
    op.create_index(op.f('ix_locations_archived_at'), 'locations', ['archived_at'], unique=False)
    op.create_index('ix_locations_org_number', 'locations', ['organization_id', 'location_number'], unique=True)
    op.create_index('ix_locations_org_project', 'locations', ['organization_id', 'project_id'], unique=False)
    op.create_index('ix_locations_org_type', 'locations', ['organization_id', 'location_type'], unique=False)
    op.create_index(op.f('ix_locations_organization_id'), 'locations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_locations_project_id'), 'locations', ['project_id'], unique=False)
    op.create_table('assets',
    sa.Column('asset_number', sa.String(length=20), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('manufacturer', sa.String(length=150), nullable=True),
    sa.Column('model', sa.String(length=150), nullable=True),
    sa.Column('serial_number', sa.String(length=150), nullable=True),
    sa.Column('year_of_manufacture', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ownership_type', sa.Enum('OWNED', 'LEASED', 'RENTED', 'CLIENT_OWNED', 'OTHER', name='ownership_type'), nullable=False),
    sa.Column('engine_number', sa.String(length=150), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('meter_type', sa.Enum('ENGINE_HOURS', 'OPERATING_HOURS', 'ODOMETER_KM', 'NONE', name='meter_type'), nullable=False),
    sa.Column('current_meter_reading', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'OPERATING', 'MOBILIZING', 'STANDBY', 'UNDER_MAINTENANCE', 'BREAKDOWN', 'OUT_OF_SERVICE', 'DISPOSED', name='asset_status'), nullable=False),
    sa.Column('default_location_id', sa.Uuid(), nullable=True),
    sa.Column('responsible_employee_id', sa.Uuid(), nullable=True),
    sa.Column('photo_url', sa.String(length=1024), nullable=True),
    sa.Column('warranty_expiry_date', sa.Date(), nullable=True),
    sa.Column('insurance_expiry_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['asset_categories.id'], name=op.f('fk_assets_category_id_asset_categories')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_assets_created_by_id_users')),
    sa.ForeignKeyConstraint(['default_location_id'], ['locations.id'], name=op.f('fk_assets_default_location_id_locations')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_assets_organization_id_organizations')),
    sa.ForeignKeyConstraint(['responsible_employee_id'], ['employees.id'], name=op.f('fk_assets_responsible_employee_id_employees')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_assets_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    op.create_index(op.f('ix_assets_archived_at'), 'assets', ['archived_at'], unique=False)
    op.create_index(op.f('ix_assets_category_id'), 'assets', ['category_id'], unique=False)
    op.create_index('ix_assets_org_category', 'assets', ['organization_id', 'category_id'], unique=False)
    op.create_index('ix_assets_org_location', 'assets', ['organization_id', 'default_location_id'], unique=False)
    op.create_index('ix_assets_org_number', 'assets', ['organization_id', 'asset_number'], unique=True)
    op.create_index('ix_assets_org_responsible', 'assets', ['organization_id', 'responsible_employee_id'], unique=False)
    op.create_index('ix_assets_org_status', 'assets', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_assets_organization_id'), 'assets', ['organization_id'], unique=False)
    op.create_table('employee_assignments',
    sa.Column('assignment_number', sa.String(length=20), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('role_on_project', sa.String(length=150), nullable=True),
    sa.Column('supervisor_id', sa.Uuid(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('rotation_pattern', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='assignment_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_employee_assignments_created_by_id_users')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_assignments_employee_id_employees')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_employee_assignments_location_id_locations')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_employee_assignments_organization_id_organizations')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_employee_assignments_project_id_projects')),
    sa.ForeignKeyConstraint(['supervisor_id'], ['employees.id'], name=op.f('fk_employee_assignments_supervisor_id_employees')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_employee_assignments_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_assignments'))
    )
    op.create_index('ix_employee_assignments_employee', 'employee_assignments', ['organization_id', 'employee_id', 'status'], unique=False)
    op.create_index(op.f('ix_employee_assignments_employee_id'), 'employee_assignments', ['employee_id'], unique=False)
    op.create_index('ix_employee_assignments_number', 'employee_assignments', ['organization_id', 'assignment_number'], unique=True)
    op.create_index(op.f('ix_employee_assignments_organization_id'), 'employee_assignments', ['organization_id'], unique=False)
    op.create_index('ix_employee_assignments_project', 'employee_assignments', ['organization_id', 'project_id', 'status'], unique=False)
    op.create_index(op.f('ix_employee_assignments_project_id'), 'employee_assignments', ['project_id'], unique=False)
    op.create_table('asset_assignments',
    sa.Column('assignment_number', sa.String(length=20), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('responsible_employee_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('starting_meter', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ending_meter', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='asset_assignment_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_assignments_asset_id_assets')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_asset_assignments_created_by_id_users')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_asset_assignments_location_id_locations')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_asset_assignments_organization_id_organizations')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_asset_assignments_project_id_projects')),
    sa.ForeignKeyConstraint(['responsible_employee_id'], ['employees.id'], name=op.f('fk_asset_assignments_responsible_employee_id_employees')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_asset_assignments_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_assignments'))
    )
    op.create_index('ix_asset_assignments_asset', 'asset_assignments', ['organization_id', 'asset_id', 'status'], unique=False)
    op.create_index(op.f('ix_asset_assignments_asset_id'), 'asset_assignments', ['asset_id'], unique=False)
    op.create_index('ix_asset_assignments_number', 'asset_assignments', ['organization_id', 'assignment_number'], unique=True)
    op.create_index(op.f('ix_asset_assignments_organization_id'), 'asset_assignments', ['organization_id'], unique=False)
    op.create_index('ix_asset_assignments_project', 'asset_assignments', ['organization_id', 'project_id', 'status'], unique=False)
    op.create_index(op.f('ix_asset_assignments_project_id'), 'asset_assignments', ['project_id'], unique=False)
    op.create_table('asset_components',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('component_type', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=150), nullable=True),
    sa.Column('model', sa.String(length=150), nullable=True),
    sa.Column('serial_number', sa.String(length=150), nullable=True),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('meter_at_installation', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('expected_life_hours', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.Enum('INSTALLED', 'REMOVED', 'FAILED', name='component_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_components_asset_id_assets')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_asset_components_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_components'))
    )
    op.create_index('ix_asset_components_asset', 'asset_components', ['organization_id', 'asset_id'], unique=False)
    op.create_index(op.f('ix_asset_components_asset_id'), 'asset_components', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_components_organization_id'), 'asset_components', ['organization_id'], unique=False)
    op.create_table('asset_meter_readings',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('reading', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reading_type', sa.Enum('ENGINE_HOURS', 'OPERATING_HOURS', 'ODOMETER_KM', name='reading_type'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('recorded_by_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_meter_readings_asset_id_assets')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_asset_meter_readings_location_id_locations')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_asset_meter_readings_organization_id_organizations')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_asset_meter_readings_project_id_projects')),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], name=op.f('fk_asset_meter_readings_recorded_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_meter_readings'))
    )
    op.create_index(op.f('ix_asset_meter_readings_asset_id'), 'asset_meter_readings', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_meter_readings_organization_id'), 'asset_meter_readings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_asset_meter_readings_recorded_at'), 'asset_meter_readings', ['recorded_at'], unique=False)
    op.create_index('ix_meter_readings_asset_time', 'asset_meter_readings', ['organization_id', 'asset_id', 'recorded_at'], unique=False)
    op.create_index('ix_meter_readings_asset_type', 'asset_meter_readings', ['organization_id', 'asset_id', 'reading_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_meter_readings_asset_type', table_name='asset_meter_readings')
    op.drop_index('ix_meter_readings_asset_time', table_name='asset_meter_readings')
    op.drop_index(op.f('ix_asset_meter_readings_recorded_at'), table_name='asset_meter_readings')
    op.drop_index(op.f('ix_asset_meter_readings_organization_id'), table_name='asset_meter_readings')
    op.drop_index(op.f('ix_asset_meter_readings_asset_id'), table_name='asset_meter_readings')
    op.drop_table('asset_meter_readings')
    op.drop_index(op.f('ix_asset_components_organization_id'), table_name='asset_components')
    op.drop_index(op.f('ix_asset_components_asset_id'), table_name='asset_components')
    op.drop_index('ix_asset_components_asset', table_name='asset_components')
    op.drop_table('asset_components')
    op.drop_index(op.f('ix_asset_assignments_project_id'), table_name='asset_assignments')
    op.drop_index('ix_asset_assignments_project', table_name='asset_assignments')
    op.drop_index(op.f('ix_asset_assignments_organization_id'), table_name='asset_assignments')
    op.drop_index('ix_asset_assignments_number', table_name='asset_assignments')
    op.drop_index(op.f('ix_asset_assignments_asset_id'), table_name='asset_assignments')
    op.drop_index('ix_asset_assignments_asset', table_name='asset_assignments')
    op.drop_table('asset_assignments')
    op.drop_index(op.f('ix_employee_assignments_project_id'), table_name='employee_assignments')
    op.drop_index('ix_employee_assignments_project', table_name='employee_assignments')
    op.drop_index(op.f('ix_employee_assignments_organization_id'), table_name='employee_assignments')
    op.drop_index('ix_employee_assignments_number', table_name='employee_assignments')
    op.drop_index(op.f('ix_employee_assignments_employee_id'), table_name='employee_assignments')
    op.drop_index('ix_employee_assignments_employee', table_name='employee_assignments')
    op.drop_table('employee_assignments')
    op.drop_index(op.f('ix_assets_organization_id'), table_name='assets')
    op.drop_index('ix_assets_org_status', table_name='assets')
    op.drop_index('ix_assets_org_responsible', table_name='assets')
    op.drop_index('ix_assets_org_number', table_name='assets')
    op.drop_index('ix_assets_org_location', table_name='assets')
    op.drop_index('ix_assets_org_category', table_name='assets')
    op.drop_index(op.f('ix_assets_category_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_archived_at'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_locations_project_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_organization_id'), table_name='locations')
    op.drop_index('ix_locations_org_type', table_name='locations')
    op.drop_index('ix_locations_org_project', table_name='locations')
    op.drop_index('ix_locations_org_number', table_name='locations')
    op.drop_index(op.f('ix_locations_archived_at'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_index('ix_projects_org_status', table_name='projects')
    op.drop_index('ix_projects_org_number', table_name='projects')
    op.drop_index('ix_projects_org_manager', table_name='projects')
    op.drop_index('ix_projects_org_client', table_name='projects')
    op.drop_index(op.f('ix_projects_client_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_archived_at'), table_name='projects')
    op.drop_table('projects')
    op.drop_index('uq_employee_skills_employee_skill', table_name='employee_skills')
    op.drop_index('ix_employee_skills_skill', table_name='employee_skills')
    op.drop_index(op.f('ix_employee_skills_organization_id'), table_name='employee_skills')
    op.drop_index(op.f('ix_employee_skills_employee_id'), table_name='employee_skills')
    op.drop_table('employee_skills')
    op.drop_index(op.f('ix_employee_documents_organization_id'), table_name='employee_documents')
    op.drop_index('ix_employee_documents_expiry', table_name='employee_documents')
    op.drop_index(op.f('ix_employee_documents_employee_id'), table_name='employee_documents')
    op.drop_index('ix_employee_documents_employee', table_name='employee_documents')
    op.drop_index(op.f('ix_employee_documents_archived_at'), table_name='employee_documents')
    op.drop_table('employee_documents')
    op.drop_index(op.f('ix_employees_organization_id'), table_name='employees')
    op.drop_index('ix_employees_org_supervisor', table_name='employees')
    op.drop_index('ix_employees_org_status', table_name='employees')
    op.drop_index('ix_employees_org_number', table_name='employees')
    op.drop_index('ix_employees_org_department', table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_archived_at'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_clients_organization_id'), table_name='clients')
    op.drop_index('ix_clients_org_number', table_name='clients')
    op.drop_index(op.f('ix_clients_archived_at'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_skills_organization_id'), table_name='skills')
    op.drop_index('ix_skills_org_name', table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_business_counters_organization_id'), table_name='business_counters')
    op.drop_table('business_counters')
    op.drop_index('ix_asset_categories_parent', table_name='asset_categories')
    op.drop_index(op.f('ix_asset_categories_organization_id'), table_name='asset_categories')
    op.drop_index('ix_asset_categories_org_name', table_name='asset_categories')
    op.drop_index(op.f('ix_asset_categories_archived_at'), table_name='asset_categories')
    op.drop_table('asset_categories')
    # Drop PostgreSQL enum types so downgrade -> upgrade cycles work.
    for enum_name in [
        "reading_type",
        "component_status",
        "asset_assignment_status",
        "meter_type",
        "asset_status",
        "ownership_type",
        "assignment_status",
        "location_type",
        "project_status",
        "document_type",
        "employment_status",
        "employment_type",
    ]:
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
