"""asset documents and document storage paths

Revision ID: 592b1794840e
Revises: b345494143eb
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '592b1794840e'
down_revision = 'b345494143eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_documents',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', postgresql.ENUM('CV', 'EMPLOYMENT_CONTRACT', 'DRIVERS_LICENSE', 'PASSPORT', 'WORK_PERMIT', 'TRAINING_CERTIFICATE', 'MEDICAL_CERTIFICATE', 'SAFETY_CERTIFICATE', 'OTHER', name='document_type', create_type=False), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('file_url', sa.String(length=1024), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('issuing_authority', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_documents_asset_id_assets')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_asset_documents_created_by_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_asset_documents_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_documents'))
    )
    op.create_index(op.f('ix_asset_documents_archived_at'), 'asset_documents', ['archived_at'], unique=False)
    op.create_index('ix_asset_documents_asset', 'asset_documents', ['organization_id', 'asset_id'], unique=False)
    op.create_index(op.f('ix_asset_documents_asset_id'), 'asset_documents', ['asset_id'], unique=False)
    op.create_index('ix_asset_documents_expiry', 'asset_documents', ['organization_id', 'expiry_date'], unique=False)
    op.create_index(op.f('ix_asset_documents_organization_id'), 'asset_documents', ['organization_id'], unique=False)
    op.add_column('employee_documents', sa.Column('storage_path', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_documents', 'storage_path')
    op.drop_index(op.f('ix_asset_documents_organization_id'), table_name='asset_documents')
    op.drop_index('ix_asset_documents_expiry', table_name='asset_documents')
    op.drop_index(op.f('ix_asset_documents_asset_id'), table_name='asset_documents')
    op.drop_index('ix_asset_documents_asset', table_name='asset_documents')
    op.drop_index(op.f('ix_asset_documents_archived_at'), table_name='asset_documents')
    op.drop_table('asset_documents')
    # ### end Alembic commands ###
