"""workforce expansion: departments positions family emergency resumes qualifications training licenses rotations authorizations

Revision ID: 13156ff3fcde
Revises: 592b1794840e
"""
from alembic import op
import sqlalchemy as sa


revision = '13156ff3fcde'
down_revision = '592b1794840e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Workforce expansion: extend existing enum value sets (transactional
    # rename-create-cast-drop; downgrade intentionally leaves expanded sets).
    op.execute("ALTER TYPE employment_type RENAME TO employment_type_old")
    sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'CASUAL', 'TEMPORARY', 'CONSULTANT', 'INTERN', name='employment_type').create(op.get_bind())
    op.execute("ALTER TABLE employees ALTER COLUMN employment_type TYPE employment_type USING employment_type::text::employment_type")
    op.execute("DROP TYPE employment_type_old")
    op.execute("ALTER TYPE employment_status RENAME TO employment_status_old")
    sa.Enum('ACTIVE', 'ON_LEAVE', 'OFF_ROTATION', 'SUSPENDED', 'EXITED', 'RESIGNED', 'TERMINATED', 'RETIRED', 'DECEASED', name='employment_status').create(op.get_bind())
    op.execute("ALTER TABLE employees ALTER COLUMN employment_status TYPE employment_status USING employment_status::text::employment_status")
    op.execute("DROP TYPE employment_status_old")
    op.execute("ALTER TYPE document_type RENAME TO document_type_old")
    sa.Enum('CV', 'NATIONAL_ID', 'PASSPORT', 'DRIVERS_LICENSE', 'WORK_PERMIT', 'EMPLOYMENT_CONTRACT', 'MEDICAL_CERTIFICATE', 'SAFETY_CERTIFICATE', 'TRAINING_CERTIFICATE', 'EDUCATIONAL_CERTIFICATE', 'TRADE_CERTIFICATE', 'PROFESSIONAL_CERTIFICATE', 'INSURANCE_DOCUMENT', 'POLICE_CLEARANCE', 'OTHER', name='document_type').create(op.get_bind())
    op.execute("ALTER TABLE employee_documents ALTER COLUMN document_type TYPE document_type USING document_type::text::document_type")
    op.execute("ALTER TABLE asset_documents ALTER COLUMN document_type TYPE document_type USING document_type::text::document_type")
    op.execute("DROP TYPE document_type_old")
    # Preserve existing contact data by renaming (not dropping) repurposed columns.
    op.alter_column('employees', 'email', new_column_name='work_email')
    op.alter_column('employees', 'phone', new_column_name='primary_phone')
    op.alter_column('employees', 'address', new_column_name='residential_address')
    op.alter_column('employees', 'photo_url', new_column_name='profile_photo_url')
    op.create_table('departments',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('manager_employee_id', sa.Uuid(), nullable=True),
    sa.Column('parent_department_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['manager_employee_id'], ['employees.id'], name=op.f('fk_departments_manager_employee_id_employees')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_departments_organization_id_organizations')),
    sa.ForeignKeyConstraint(['parent_department_id'], ['departments.id'], name=op.f('fk_departments_parent_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments'))
    )
    op.create_index(op.f('ix_departments_archived_at'), 'departments', ['archived_at'], unique=False)
    op.create_index('ix_departments_org_name', 'departments', ['organization_id', 'name'], unique=True)
    op.create_index('ix_departments_org_parent', 'departments', ['organization_id', 'parent_department_id'], unique=False)
    op.create_index(op.f('ix_departments_organization_id'), 'departments', ['organization_id'], unique=False)
    op.create_table('rotation_patterns',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('days_on', sa.Integer(), nullable=False),
    sa.Column('days_off', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_rotation_patterns_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rotation_patterns'))
    )
    op.create_index(op.f('ix_rotation_patterns_archived_at'), 'rotation_patterns', ['archived_at'], unique=False)
    op.create_index('ix_rotation_patterns_org_name', 'rotation_patterns', ['organization_id', 'name'], unique=True)
    op.create_index(op.f('ix_rotation_patterns_organization_id'), 'rotation_patterns', ['organization_id'], unique=False)
    op.create_table('employee_family_members',
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('relationship_type', sa.Enum('SPOUSE', 'CHILD', 'PARENT', 'SIBLING', 'GUARDIAN', 'PARTNER', 'RELATIVE', 'OTHER', name='relationship_type'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('occupation', sa.String(length=150), nullable=True),
    sa.Column('employer', sa.String(length=200), nullable=True),
    sa.Column('is_dependent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_next_of_kin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_primary_next_of_kin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_emergency_contact', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('dependency_start_date', sa.Date(), nullable=True),
    sa.Column('dependency_end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_employee_family_members_created_by_id_users')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_family_members_employee_id_employees')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_employee_family_members_organization_id_organizations')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_employee_family_members_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_family_members'))
    )
    op.create_index(op.f('ix_employee_family_members_archived_at'), 'employee_family_members', ['archived_at'], unique=False)
    op.create_index(op.f('ix_employee_family_members_employee_id'), 'employee_family_members', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_family_members_organization_id'), 'employee_family_members', ['organization_id'], unique=False)
    op.create_index('ix_family_dependent', 'employee_family_members', ['organization_id', 'employee_id', 'is_dependent'], unique=False)
    op.create_index('ix_family_employee', 'employee_family_members', ['organization_id', 'employee_id'], unique=False)
    op.create_index('ix_family_next_of_kin', 'employee_family_members', ['organization_id', 'employee_id', 'is_next_of_kin'], unique=False)
    op.create_table('employee_resumes',
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_resumes_employee_id_employees')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_employee_resumes_organization_id_organizations')),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_employee_resumes_uploaded_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_resumes'))
    )
    op.create_index(op.f('ix_employee_resumes_archived_at'), 'employee_resumes', ['archived_at'], unique=False)
    op.create_index(op.f('ix_employee_resumes_employee_id'), 'employee_resumes', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_resumes_organization_id'), 'employee_resumes', ['organization_id'], unique=False)
    op.create_index('ix_resumes_current', 'employee_resumes', ['organization_id', 'employee_id', 'is_current'], unique=False)
    op.create_index('ix_resumes_employee', 'employee_resumes', ['organization_id', 'employee_id'], unique=False)
    op.create_index('uq_resumes_employee_version', 'employee_resumes', ['organization_id', 'employee_id', 'version'], unique=True)
    op.create_table('positions',
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('is_field_role', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_positions_department_id_departments')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_positions_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions'))
    )
    op.create_index(op.f('ix_positions_archived_at'), 'positions', ['archived_at'], unique=False)
    op.create_index('ix_positions_org_department', 'positions', ['organization_id', 'department_id'], unique=False)
    op.create_index('ix_positions_org_title', 'positions', ['organization_id', 'title'], unique=True)
    op.create_index(op.f('ix_positions_organization_id'), 'positions', ['organization_id'], unique=False)
    op.create_table('employee_asset_authorizations',
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('asset_category_id', sa.Uuid(), nullable=True),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('authorization_type', sa.Enum('OPERATOR', 'DRIVER', 'MAINTENANCE', 'INSPECTOR', 'SUPERVISOR', 'OTHER', name='authorization_type'), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('authorized_by_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'SUSPENDED', 'REVOKED', name='authorization_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['asset_category_id'], ['asset_categories.id'], name=op.f('fk_employee_asset_authorizations_asset_category_id_asset_categories')),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_employee_asset_authorizations_asset_id_assets')),
    sa.ForeignKeyConstraint(['authorized_by_id'], ['users.id'], name=op.f('fk_employee_asset_authorizations_authorized_by_id_users')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_employee_asset_authorizations_created_by_id_users')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_asset_authorizations_employee_id_employees')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_employee_asset_authorizations_organization_id_organizations')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_employee_asset_authorizations_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_asset_authorizations'))
    )
    op.create_index('ix_authorizations_employee', 'employee_asset_authorizations', ['organization_id', 'employee_id', 'status'], unique=False)
    op.create_index(op.f('ix_employee_asset_authorizations_employee_id'), 'employee_asset_authorizations', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_asset_authorizations_organization_id'), 'employee_asset_authorizations', ['organization_id'], unique=False)
    op.create_table('employee_emergency_contacts',
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('family_member_id', sa.Uuid(), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('relationship', sa.String(length=100), nullable=True),
    sa.Column('primary_phone', sa.String(length=50), nullable=False),
    sa.Column('secondary_phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_employee_emergency_contacts_created_by_id_users')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_emergency_contacts_employee_id_employees')),
    sa.ForeignKeyConstraint(['family_member_id'], ['employee_family_members.id'], name=op.f('fk_employee_emergency_contacts_family_member_id_employee_family_members')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_employee_emergency_contacts_organization_id_organizations')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_employee_emergency_contacts_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_emergency_contacts'))
    )
    op.create_index('ix_emergency_employee', 'employee_emergency_contacts', ['organization_id', 'employee_id'], unique=False)
    op.create_index('ix_emergency_primary', 'employee_emergency_contacts', ['organization_id', 'employee_id', 'is_primary'], unique=False)
    op.create_index(op.f('ix_employee_emergency_contacts_archived_at'), 'employee_emergency_contacts', ['archived_at'], unique=False)
    op.create_index(op.f('ix_employee_emergency_contacts_employee_id'), 'employee_emergency_contacts', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_emergency_contacts_organization_id'), 'employee_emergency_contacts', ['organization_id'], unique=False)
    op.create_table('employee_licenses',
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('license_type', sa.Enum('DRIVERS_LICENSE', 'HEAVY_EQUIPMENT_OPERATOR', 'DRILL_RIG_OPERATOR', 'FORKLIFT_LICENSE', 'WORK_PERMIT', 'PROFESSIONAL_REGISTRATION', 'OTHER', name='license_type'), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('issuing_authority', sa.String(length=200), nullable=True),
    sa.Column('issuing_country', sa.String(length=100), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('VALID', 'EXPIRING', 'EXPIRED', 'SUSPENDED', 'REVOKED', 'PENDING_VERIFICATION', name='license_status'), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('restrictions', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_employee_licenses_created_by_id_users')),
    sa.ForeignKeyConstraint(['document_id'], ['employee_documents.id'], name=op.f('fk_employee_licenses_document_id_employee_documents')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_licenses_employee_id_employees')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_employee_licenses_organization_id_organizations')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_employee_licenses_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_licenses'))
    )
    op.create_index(op.f('ix_employee_licenses_archived_at'), 'employee_licenses', ['archived_at'], unique=False)
    op.create_index(op.f('ix_employee_licenses_employee_id'), 'employee_licenses', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_licenses_organization_id'), 'employee_licenses', ['organization_id'], unique=False)
    op.create_index('ix_licenses_employee', 'employee_licenses', ['organization_id', 'employee_id'], unique=False)
    op.create_index('ix_licenses_expiry', 'employee_licenses', ['organization_id', 'expiry_date'], unique=False)
    op.create_index('ix_licenses_type', 'employee_licenses', ['organization_id', 'license_type'], unique=False)
    op.create_table('employee_qualifications',
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('qualification_type', sa.String(length=100), nullable=False),
    sa.Column('qualification_name', sa.String(length=200), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=True),
    sa.Column('field_of_study', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('grade_or_classification', sa.String(length=100), nullable=True),
    sa.Column('certificate_number', sa.String(length=100), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_employee_qualifications_created_by_id_users')),
    sa.ForeignKeyConstraint(['document_id'], ['employee_documents.id'], name=op.f('fk_employee_qualifications_document_id_employee_documents')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_qualifications_employee_id_employees')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_employee_qualifications_organization_id_organizations')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_employee_qualifications_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_qualifications'))
    )
    op.create_index(op.f('ix_employee_qualifications_archived_at'), 'employee_qualifications', ['archived_at'], unique=False)
    op.create_index(op.f('ix_employee_qualifications_employee_id'), 'employee_qualifications', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_qualifications_organization_id'), 'employee_qualifications', ['organization_id'], unique=False)
    op.create_index('ix_qualifications_employee', 'employee_qualifications', ['organization_id', 'employee_id'], unique=False)
    op.create_table('employee_training_records',
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('training_name', sa.String(length=200), nullable=False),
    sa.Column('training_type', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'EXPIRED', 'CANCELLED', name='training_status'), nullable=False),
    sa.Column('certificate_number', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_employee_training_records_created_by_id_users')),
    sa.ForeignKeyConstraint(['document_id'], ['employee_documents.id'], name=op.f('fk_employee_training_records_document_id_employee_documents')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_training_records_employee_id_employees')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_employee_training_records_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_training_records'))
    )
    op.create_index(op.f('ix_employee_training_records_archived_at'), 'employee_training_records', ['archived_at'], unique=False)
    op.create_index(op.f('ix_employee_training_records_employee_id'), 'employee_training_records', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_training_records_organization_id'), 'employee_training_records', ['organization_id'], unique=False)
    op.create_index('ix_training_employee', 'employee_training_records', ['organization_id', 'employee_id'], unique=False)
    op.create_index('ix_training_expiry', 'employee_training_records', ['organization_id', 'expiry_date'], unique=False)
    op.create_table('employee_rotations',
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('assignment_id', sa.Uuid(), nullable=True),
    sa.Column('rotation_pattern_id', sa.Uuid(), nullable=False),
    sa.Column('cycle_start_date', sa.Date(), nullable=False),
    sa.Column('work_start_date', sa.Date(), nullable=False),
    sa.Column('work_end_date', sa.Date(), nullable=False),
    sa.Column('off_start_date', sa.Date(), nullable=False),
    sa.Column('off_end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'ON_SITE', 'OFF_ROTATION', 'COMPLETED', 'CANCELLED', name='rotation_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['employee_assignments.id'], name=op.f('fk_employee_rotations_assignment_id_employee_assignments')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_employee_rotations_created_by_id_users')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_rotations_employee_id_employees')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_employee_rotations_organization_id_organizations')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_employee_rotations_project_id_projects')),
    sa.ForeignKeyConstraint(['rotation_pattern_id'], ['rotation_patterns.id'], name=op.f('fk_employee_rotations_rotation_pattern_id_rotation_patterns')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_employee_rotations_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_rotations'))
    )
    op.create_index(op.f('ix_employee_rotations_employee_id'), 'employee_rotations', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_rotations_organization_id'), 'employee_rotations', ['organization_id'], unique=False)
    op.create_index('ix_rotations_employee', 'employee_rotations', ['organization_id', 'employee_id', 'status'], unique=False)
    op.create_index('ix_rotations_pattern', 'employee_rotations', ['organization_id', 'rotation_pattern_id'], unique=False)
    op.add_column('employee_assignments', sa.Column('position_id', sa.Uuid(), nullable=True))
    sa.Enum('PROJECT', 'SITE', 'TEMPORARY', 'RELIEF', 'TRAINING', 'OFFICE', 'OTHER', name='assignment_type').create(op.get_bind(), checkfirst=True)
    op.add_column('employee_assignments', sa.Column('assignment_type', sa.Enum('PROJECT', 'SITE', 'TEMPORARY', 'RELIEF', 'TRAINING', 'OFFICE', 'OTHER', name='assignment_type'), server_default='PROJECT', nullable=False))
    op.add_column('employee_assignments', sa.Column('is_primary', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('employee_assignments', sa.Column('rotation_pattern_id', sa.Uuid(), nullable=True))
    op.add_column('employee_assignments', sa.Column('mobilization_date', sa.Date(), nullable=True))
    op.add_column('employee_assignments', sa.Column('demobilization_date', sa.Date(), nullable=True))
    op.create_foreign_key(op.f('fk_employee_assignments_position_id_positions'), 'employee_assignments', 'positions', ['position_id'], ['id'])
    op.create_foreign_key(op.f('fk_employee_assignments_rotation_pattern_id_rotation_patterns'), 'employee_assignments', 'rotation_patterns', ['rotation_pattern_id'], ['id'])
    op.add_column('employee_documents', sa.Column('file_size', sa.BigInteger(), nullable=True))
    op.add_column('employee_documents', sa.Column('issuing_country', sa.String(length=100), nullable=True))
    sa.Enum('PENDING', 'VERIFIED', 'REJECTED', 'EXPIRED', name='verification_status').create(op.get_bind(), checkfirst=True)
    op.add_column('employee_documents', sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', 'EXPIRED', name='verification_status'), server_default='PENDING', nullable=False))
    op.add_column('employee_documents', sa.Column('verified_by_id', sa.Uuid(), nullable=True))
    op.add_column('employee_documents', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('employee_documents', sa.Column('updated_by_id', sa.Uuid(), nullable=True))
    op.create_index('ix_employee_documents_type', 'employee_documents', ['organization_id', 'document_type'], unique=False)
    op.create_foreign_key(op.f('fk_employee_documents_updated_by_id_users'), 'employee_documents', 'users', ['updated_by_id'], ['id'])
    op.create_foreign_key(op.f('fk_employee_documents_verified_by_id_users'), 'employee_documents', 'users', ['verified_by_id'], ['id'])
    op.add_column('employee_skills', sa.Column('years_experience', sa.Integer(), nullable=True))
    sa.Enum('BASIC', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', 'CERTIFIED', name='proficiency_level').create(op.get_bind(), checkfirst=True)
    op.execute("ALTER TABLE employee_skills ALTER COLUMN proficiency_level TYPE proficiency_level USING proficiency_level::text::proficiency_level")
    op.add_column('employees', sa.Column('gender', sa.String(length=30), nullable=True))
    sa.Enum('SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', 'SEPARATED', 'OTHER', 'UNKNOWN', name='marital_status').create(op.get_bind(), checkfirst=True)
    op.add_column('employees', sa.Column('marital_status', sa.Enum('SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', 'SEPARATED', 'OTHER', 'UNKNOWN', name='marital_status'), nullable=True))
    op.add_column('employees', sa.Column('personal_email', sa.String(length=255), nullable=True))
    op.add_column('employees', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('county_or_region', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('department_id', sa.Uuid(), nullable=True))
    op.add_column('employees', sa.Column('position_id', sa.Uuid(), nullable=True))
    op.add_column('employees', sa.Column('probation_end_date', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('confirmation_date', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('contract_start_date', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('contract_end_date', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('termination_reason', sa.Text(), nullable=True))
    op.add_column('employees', sa.Column('home_location_id', sa.Uuid(), nullable=True))
    op.add_column('employees', sa.Column('bio', sa.Text(), nullable=True))
    op.alter_column('employees', 'employee_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('employees', 'job_title',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_org_department'), table_name='employees')
    op.create_index('ix_employees_org_department', 'employees', ['organization_id', 'department_id'], unique=False)
    op.create_index('ix_employees_last_name', 'employees', ['organization_id', 'last_name'], unique=False)
    op.create_index('ix_employees_org_position', 'employees', ['organization_id', 'position_id'], unique=False)
    op.create_index('ix_employees_org_work_email', 'employees', ['organization_id', 'work_email'], unique=True)
    op.create_index(op.f('ix_employees_work_email'), 'employees', ['work_email'], unique=False)
    op.create_foreign_key(op.f('fk_employees_home_location_id_locations'), 'employees', 'locations', ['home_location_id'], ['id'])
    op.create_foreign_key(op.f('fk_employees_department_id_departments'), 'employees', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(op.f('fk_employees_position_id_positions'), 'employees', 'positions', ['position_id'], ['id'])
    op.drop_column('employees', 'emergency_contact_name')
    op.drop_column('employees', 'emergency_contact_relationship')
    op.drop_column('employees', 'emergency_contact_phone')
    op.add_column('skills', sa.Column('category', sa.String(length=100), nullable=True))
    op.create_check_constraint(op.f('ck_employees_termination_after_hire'), 'employees', sa.text('termination_date IS NULL OR hire_date IS NULL OR termination_date >= hire_date'))
    op.create_check_constraint(op.f('ck_employees_contract_dates'), 'employees', sa.text('contract_end_date IS NULL OR contract_start_date IS NULL OR contract_end_date >= contract_start_date'))
    op.alter_column('employees', 'profile_photo_url', existing_type=sa.VARCHAR(length=1024), type_=sa.Text(), existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_employees_termination_after_hire'), 'employees', type_='check')
    op.drop_constraint(op.f('ck_employees_contract_dates'), 'employees', type_='check')
    op.drop_column('skills', 'category')
    op.add_column('employees', sa.Column('emergency_contact_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('emergency_contact_relationship', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('emergency_contact_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.alter_column('employees', 'work_email', new_column_name='email')
    op.alter_column('employees', 'primary_phone', new_column_name='phone')
    op.alter_column('employees', 'residential_address', new_column_name='address')
    op.alter_column('employees', 'profile_photo_url', new_column_name='photo_url')
    op.alter_column('employees', 'photo_url', existing_type=sa.Text(), type_=sa.VARCHAR(length=1024), existing_nullable=True)
    op.drop_constraint(op.f('fk_employees_position_id_positions'), 'employees', type_='foreignkey')
    op.drop_constraint(op.f('fk_employees_department_id_departments'), 'employees', type_='foreignkey')
    op.drop_constraint(op.f('fk_employees_home_location_id_locations'), 'employees', type_='foreignkey')
    op.drop_index(op.f('ix_employees_work_email'), table_name='employees')
    op.drop_index('ix_employees_org_work_email', table_name='employees')
    op.drop_index('ix_employees_org_position', table_name='employees')
    op.drop_index('ix_employees_last_name', table_name='employees')
    op.drop_index('ix_employees_org_department', table_name='employees')
    op.create_index(op.f('ix_employees_org_department'), 'employees', ['organization_id', 'department'], unique=False)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=False)
    op.alter_column('employees', 'job_title',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('employees', 'employee_number',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('employees', 'bio')
    op.drop_column('employees', 'home_location_id')
    op.drop_column('employees', 'termination_reason')
    op.drop_column('employees', 'contract_end_date')
    op.drop_column('employees', 'contract_start_date')
    op.drop_column('employees', 'confirmation_date')
    op.drop_column('employees', 'probation_end_date')
    op.drop_column('employees', 'position_id')
    op.drop_column('employees', 'department_id')
    op.drop_column('employees', 'country')
    op.drop_column('employees', 'county_or_region')
    op.drop_column('employees', 'city')
    op.drop_column('employees', 'personal_email')
    op.drop_column('employees', 'marital_status')
    op.drop_column('employees', 'gender')
    op.execute("ALTER TABLE employee_skills ALTER COLUMN proficiency_level TYPE VARCHAR(50) USING proficiency_level::text")
    op.drop_column('employee_skills', 'years_experience')
    op.drop_constraint(op.f('fk_employee_documents_verified_by_id_users'), 'employee_documents', type_='foreignkey')
    op.drop_constraint(op.f('fk_employee_documents_updated_by_id_users'), 'employee_documents', type_='foreignkey')
    op.drop_index('ix_employee_documents_type', table_name='employee_documents')
    op.drop_column('employee_documents', 'updated_by_id')
    op.drop_column('employee_documents', 'verified_at')
    op.drop_column('employee_documents', 'verified_by_id')
    op.drop_column('employee_documents', 'verification_status')
    op.drop_column('employee_documents', 'issuing_country')
    op.drop_column('employee_documents', 'file_size')
    op.drop_constraint(op.f('fk_employee_assignments_rotation_pattern_id_rotation_patterns'), 'employee_assignments', type_='foreignkey')
    op.drop_constraint(op.f('fk_employee_assignments_position_id_positions'), 'employee_assignments', type_='foreignkey')
    op.drop_column('employee_assignments', 'demobilization_date')
    op.drop_column('employee_assignments', 'mobilization_date')
    op.drop_column('employee_assignments', 'rotation_pattern_id')
    op.drop_column('employee_assignments', 'is_primary')
    op.drop_column('employee_assignments', 'assignment_type')
    op.drop_column('employee_assignments', 'position_id')
    op.drop_index('ix_rotations_pattern', table_name='employee_rotations')
    op.drop_index('ix_rotations_employee', table_name='employee_rotations')
    op.drop_index(op.f('ix_employee_rotations_organization_id'), table_name='employee_rotations')
    op.drop_index(op.f('ix_employee_rotations_employee_id'), table_name='employee_rotations')
    op.drop_table('employee_rotations')
    op.drop_index('ix_training_expiry', table_name='employee_training_records')
    op.drop_index('ix_training_employee', table_name='employee_training_records')
    op.drop_index(op.f('ix_employee_training_records_organization_id'), table_name='employee_training_records')
    op.drop_index(op.f('ix_employee_training_records_employee_id'), table_name='employee_training_records')
    op.drop_index(op.f('ix_employee_training_records_archived_at'), table_name='employee_training_records')
    op.drop_table('employee_training_records')
    op.drop_index('ix_qualifications_employee', table_name='employee_qualifications')
    op.drop_index(op.f('ix_employee_qualifications_organization_id'), table_name='employee_qualifications')
    op.drop_index(op.f('ix_employee_qualifications_employee_id'), table_name='employee_qualifications')
    op.drop_index(op.f('ix_employee_qualifications_archived_at'), table_name='employee_qualifications')
    op.drop_table('employee_qualifications')
    op.drop_index('ix_licenses_type', table_name='employee_licenses')
    op.drop_index('ix_licenses_expiry', table_name='employee_licenses')
    op.drop_index('ix_licenses_employee', table_name='employee_licenses')
    op.drop_index(op.f('ix_employee_licenses_organization_id'), table_name='employee_licenses')
    op.drop_index(op.f('ix_employee_licenses_employee_id'), table_name='employee_licenses')
    op.drop_index(op.f('ix_employee_licenses_archived_at'), table_name='employee_licenses')
    op.drop_table('employee_licenses')
    op.drop_index(op.f('ix_employee_emergency_contacts_organization_id'), table_name='employee_emergency_contacts')
    op.drop_index(op.f('ix_employee_emergency_contacts_employee_id'), table_name='employee_emergency_contacts')
    op.drop_index(op.f('ix_employee_emergency_contacts_archived_at'), table_name='employee_emergency_contacts')
    op.drop_index('ix_emergency_primary', table_name='employee_emergency_contacts')
    op.drop_index('ix_emergency_employee', table_name='employee_emergency_contacts')
    op.drop_table('employee_emergency_contacts')
    op.drop_index(op.f('ix_employee_asset_authorizations_organization_id'), table_name='employee_asset_authorizations')
    op.drop_index(op.f('ix_employee_asset_authorizations_employee_id'), table_name='employee_asset_authorizations')
    op.drop_index('ix_authorizations_employee', table_name='employee_asset_authorizations')
    op.drop_table('employee_asset_authorizations')
    op.drop_index(op.f('ix_positions_organization_id'), table_name='positions')
    op.drop_index('ix_positions_org_title', table_name='positions')
    op.drop_index('ix_positions_org_department', table_name='positions')
    op.drop_index(op.f('ix_positions_archived_at'), table_name='positions')
    op.drop_table('positions')
    op.drop_index('uq_resumes_employee_version', table_name='employee_resumes')
    op.drop_index('ix_resumes_employee', table_name='employee_resumes')
    op.drop_index('ix_resumes_current', table_name='employee_resumes')
    op.drop_index(op.f('ix_employee_resumes_organization_id'), table_name='employee_resumes')
    op.drop_index(op.f('ix_employee_resumes_employee_id'), table_name='employee_resumes')
    op.drop_index(op.f('ix_employee_resumes_archived_at'), table_name='employee_resumes')
    op.drop_table('employee_resumes')
    op.drop_index('ix_family_next_of_kin', table_name='employee_family_members')
    op.drop_index('ix_family_employee', table_name='employee_family_members')
    op.drop_index('ix_family_dependent', table_name='employee_family_members')
    op.drop_index(op.f('ix_employee_family_members_organization_id'), table_name='employee_family_members')
    op.drop_index(op.f('ix_employee_family_members_employee_id'), table_name='employee_family_members')
    op.drop_index(op.f('ix_employee_family_members_archived_at'), table_name='employee_family_members')
    op.drop_table('employee_family_members')
    op.drop_index(op.f('ix_rotation_patterns_organization_id'), table_name='rotation_patterns')
    op.drop_index('ix_rotation_patterns_org_name', table_name='rotation_patterns')
    op.drop_index(op.f('ix_rotation_patterns_archived_at'), table_name='rotation_patterns')
    op.drop_table('rotation_patterns')
    op.drop_index(op.f('ix_departments_organization_id'), table_name='departments')
    op.drop_index('ix_departments_org_parent', table_name='departments')
    op.drop_index('ix_departments_org_name', table_name='departments')
    op.drop_index(op.f('ix_departments_archived_at'), table_name='departments')
    op.drop_table('departments')
    for enum_name in [
        "proficiency_level",
        "marital_status",
        "relationship_type",
        "verification_status",
        "training_status",
        "license_type",
        "license_status",
        "assignment_type",
        "rotation_status",
        "authorization_type",
        "authorization_status",
    ]:
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
