"""Complete asset domain: history, media, inspections, defects, insurance, registrations

Revision ID: 8f2a3b5c6d7e
Revises: 13156ff3fcde
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '8f2a3b5c6d7e'
down_revision = '13156ff3fcde'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Extend asset_categories table with additional fields
    op.add_column('asset_categories', sa.Column('code', sa.String(length=30), nullable=True))
    op.add_column('asset_categories', sa.Column('default_meter_type', sa.String(length=30), nullable=True))
    op.add_column('asset_categories', sa.Column('is_mobile', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('asset_categories', sa.Column('requires_registration', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('asset_categories', sa.Column('requires_insurance', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('asset_categories', sa.Column('requires_operator', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('asset_categories', sa.Column('created_by_id', sa.Uuid(), nullable=True))
    op.add_column('asset_categories', sa.Column('updated_by_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_asset_categories_created_by_id_users'), 'asset_categories', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(op.f('fk_asset_categories_updated_by_id_users'), 'asset_categories', 'users', ['updated_by_id'], ['id'])
    
    # Extend asset_components table with additional fields
    op.add_column('asset_components', sa.Column('parent_component_id', sa.Uuid(), nullable=True))
    op.add_column('asset_components', sa.Column('component_number', sa.String(length=50), nullable=True))
    op.add_column('asset_components', sa.Column('part_number', sa.String(length=150), nullable=True))
    op.add_column('asset_components', sa.Column('expected_life_cycles', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('asset_components', sa.Column('removal_date', sa.Date(), nullable=True))
    op.add_column('asset_components', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('asset_components', sa.Column('created_by_id', sa.Uuid(), nullable=True))
    op.add_column('asset_components', sa.Column('updated_by_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_asset_components_parent_component_id_asset_components'), 'asset_components', 'asset_components', ['parent_component_id'], ['id'])
    op.create_foreign_key(op.f('fk_asset_components_created_by_id_users'), 'asset_components', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(op.f('fk_asset_components_updated_by_id_users'), 'asset_components', 'users', ['updated_by_id'], ['id'])
    
    # Extend assets table with additional fields for complete asset master record
    op.add_column('assets', sa.Column('engine_manufacturer', sa.String(length=150), nullable=True))
    op.add_column('assets', sa.Column('engine_model', sa.String(length=150), nullable=True))
    op.add_column('assets', sa.Column('chassis_number', sa.String(length=150), nullable=True))
    op.add_column('assets', sa.Column('vin', sa.String(length=150), nullable=True))
    op.add_column('assets', sa.Column('ownership_entity', sa.String(length=200), nullable=True))
    op.add_column('assets', sa.Column('purchase_currency', sa.String(length=10), nullable=True))
    op.add_column('assets', sa.Column('commission_date', sa.Date(), nullable=True))
    op.add_column('assets', sa.Column('supplier_id', sa.Uuid(), nullable=True))
    op.add_column('assets', sa.Column('warranty_start_date', sa.Date(), nullable=True))
    op.add_column('assets', sa.Column('expected_service_life_years', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('assets', sa.Column('residual_value', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('assets', sa.Column('primary_operator_id', sa.Uuid(), nullable=True))
    op.add_column('assets', sa.Column('profile_photo_url', sa.Text(), nullable=True))
    op.add_column('assets', sa.Column('qr_code_value', sa.String(length=255), nullable=True))
    op.add_column('assets', sa.Column('barcode_value', sa.String(length=255), nullable=True))
    
    # Add foreign key for primary_operator
    op.create_foreign_key(op.f('fk_assets_primary_operator_id_employees'), 'assets', 'employees', ['primary_operator_id'], ['id'])
    
    # Create indexes for new asset fields
    op.create_index(op.f('ix_assets_primary_operator'), 'assets', ['primary_operator_id'], unique=False)
    op.create_index('ix_assets_org_registration', 'assets', ['organization_id', 'registration_number'], unique=False)
    op.create_index('ix_assets_org_serial', 'assets', ['organization_id', 'serial_number'], unique=True)
    op.create_index('ix_assets_org_operator', 'assets', ['organization_id', 'primary_operator_id'], unique=False)
    
    # Update asset_status enum to add missing values
    op.execute("ALTER TYPE asset_status RENAME TO asset_status_old")
    sa.Enum('AVAILABLE', 'ASSIGNED', 'OPERATING', 'STANDBY', 'MOBILIZING', 'DEMOBILIZING', 'UNDER_MAINTENANCE', 'BREAKDOWN', 'OUT_OF_SERVICE', 'QUARANTINED', 'DISPOSED', 'LOST', 'STOLEN', name='asset_status').create(op.get_bind())
    op.execute("ALTER TABLE assets ALTER COLUMN status TYPE asset_status USING status::text::asset_status")
    op.execute("DROP TYPE asset_status_old")
    
    # Update meter_type enum to add ODOMETER_MILES and CYCLES
    op.execute("ALTER TYPE meter_type RENAME TO meter_type_old")
    sa.Enum('ENGINE_HOURS', 'OPERATING_HOURS', 'ODOMETER_KM', 'ODOMETER_MILES', 'CYCLES', 'NONE', name='meter_type').create(op.get_bind())
    op.execute("ALTER TABLE assets ALTER COLUMN meter_type TYPE meter_type USING meter_type::text::meter_type")
    op.execute("ALTER TABLE asset_categories ALTER COLUMN default_meter_type TYPE meter_type USING default_meter_type::text::meter_type")
    op.execute("DROP TYPE meter_type_old")
    
    # Add reading_type enum if it doesn't exist
    reading_type_enum = postgresql.ENUM('ENGINE_HOURS', 'OPERATING_HOURS', 'ODOMETER_KM', 'ODOMETER_MILES', 'CYCLES', name='reading_type', create_type=False)
    reading_type_enum.create(op.get_bind(), checkfirst=True)
    
    # Add ownership enum values
    op.execute("ALTER TYPE ownership_type RENAME TO ownership_type_old")
    sa.Enum('OWNED', 'LEASED', 'RENTED', 'CLIENT_OWNED', 'THIRD_PARTY', 'OTHER', name='ownership_type').create(op.get_bind())
    op.execute("ALTER TABLE assets ALTER COLUMN ownership_type TYPE ownership_type USING ownership_type::text::ownership_type")
    op.execute("DROP TYPE ownership_type_old")
    
    # Add assignment_reason column to asset_assignments
    op.add_column('asset_assignments', sa.Column('assignment_reason', sa.String(length=200), nullable=True))
    op.add_column('asset_assignments', sa.Column('primary_operator_id', sa.Uuid(), nullable=True))
    op.add_column('asset_assignments', sa.Column('expected_return_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(op.f('fk_asset_assignments_primary_operator_id_employees'), 'asset_assignments', 'employees', ['primary_operator_id'], ['id'])
    
    # Extend asset_meter_readings table with additional fields
    op.add_column('asset_meter_readings', sa.Column('evidence_photo_url', sa.Text(), nullable=True))
    op.add_column('asset_meter_readings', sa.Column('is_adjustment', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('asset_meter_readings', sa.Column('adjustment_reason', sa.Text(), nullable=True))
    op.add_column('asset_meter_readings', sa.Column('previous_reading', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('asset_meter_readings', sa.Column('meter_replaced', sa.Boolean(), server_default='false', nullable=False))
    
    # Extend asset_documents table with additional fields
    op.add_column('asset_documents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('asset_documents', sa.Column('verification_status', sa.String(length=30), server_default='PENDING', nullable=False))
    op.add_column('asset_documents', sa.Column('verified_by_id', sa.Uuid(), nullable=True))
    op.add_column('asset_documents', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('asset_documents', sa.Column('updated_by_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_asset_documents_verified_by_id_users'), 'asset_documents', 'users', ['verified_by_id'], ['id'])
    op.create_foreign_key(op.f('fk_asset_documents_updated_by_id_users'), 'asset_documents', 'users', ['updated_by_id'], ['id'])
    
    # Create asset_location_history table
    op.create_table('asset_location_history',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meter_reading', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('recorded_by_id', sa.Uuid(), nullable=True),
    sa.Column('source_reference_type', sa.String(length=80), nullable=True),
    sa.Column('source_reference_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_location_history_asset_id_assets')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_asset_location_history_location_id_locations')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_asset_location_history_organization_id_organizations')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_asset_location_history_project_id_projects')),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], name=op.f('fk_asset_location_history_recorded_by_id_users')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_asset_location_history_created_by_id_users')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_asset_location_history_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_location_history'))
    )
    op.create_index('ix_asset_location_time', 'asset_location_history', ['organization_id', 'asset_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_asset_location_history_asset_id'), 'asset_location_history', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_location_history_organization_id'), 'asset_location_history', ['organization_id'], unique=False)
    
    # Create asset_status_history table
    op.create_table('asset_status_history',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('previous_status', sa.String(length=40), nullable=True),
    sa.Column('new_status', sa.String(length=40), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changed_by_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('source_reference_type', sa.String(length=80), nullable=True),
    sa.Column('source_reference_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_status_history_asset_id_assets')),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], name=op.f('fk_asset_status_history_changed_by_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_asset_status_history_organization_id_organizations')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_asset_status_history_location_id_locations')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_asset_status_history_project_id_projects')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_asset_status_history_created_by_id_users')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_asset_status_history_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_status_history'))
    )
    op.create_index('ix_asset_status_time', 'asset_status_history', ['organization_id', 'asset_id', 'changed_at'], unique=False)
    op.create_index(op.f('ix_asset_status_history_asset_id'), 'asset_status_history', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_status_history_organization_id'), 'asset_status_history', ['organization_id'], unique=False)
    
    # Create asset_insurance_records table
    op.create_table('asset_insurance_records',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=200), nullable=False),
    sa.Column('policy_number', sa.String(length=150), nullable=False),
    sa.Column('coverage_type', sa.String(length=100), nullable=True),
    sa.Column('coverage_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('premium_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='ACTIVE', nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint('expiry_date >= start_date', name='insurance_dates'),
    sa.CheckConstraint('coverage_amount >= 0 AND premium_amount >= 0', name='insurance_amounts'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_insurance_records_asset_id_assets')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_asset_insurance_records_organization_id_organizations')),
    sa.ForeignKeyConstraint(['document_id'], ['asset_documents.id'], name=op.f('fk_asset_insurance_records_document_id_asset_documents')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_asset_insurance_records_created_by_id_users')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_asset_insurance_records_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_insurance_records'))
    )
    op.create_index('ix_insurance_expiry', 'asset_insurance_records', ['organization_id', 'expiry_date'], unique=False)
    op.create_index(op.f('ix_asset_insurance_records_asset_id'), 'asset_insurance_records', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_insurance_records_organization_id'), 'asset_insurance_records', ['organization_id'], unique=False)
    
    # Create asset_registrations table
    op.create_table('asset_registrations',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('registration_type', sa.String(length=40), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=False),
    sa.Column('issuing_authority', sa.String(length=200), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='ACTIVE', nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint('expiry_date >= issue_date', name='registration_dates'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_registrations_asset_id_assets')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_asset_registrations_organization_id_organizations')),
    sa.ForeignKeyConstraint(['document_id'], ['asset_documents.id'], name=op.f('fk_asset_registrations_document_id_asset_documents')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_asset_registrations_created_by_id_users')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_asset_registrations_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_registrations'))
    )
    op.create_index('ix_registration_expiry', 'asset_registrations', ['organization_id', 'expiry_date'], unique=False)
    op.create_index(op.f('ix_asset_registrations_asset_id'), 'asset_registrations', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_registrations_organization_id'), 'asset_registrations', ['organization_id'], unique=False)
    
    # Create asset_ownership_history table
    op.create_table('asset_ownership_history',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('ownership_type', sa.String(length=30), nullable=False),
    sa.Column('owner_or_provider', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('purchase_or_contract_reference', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint('end_date >= start_date', name='ownership_dates'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_ownership_history_asset_id_assets')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_asset_ownership_history_organization_id_organizations')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_asset_ownership_history_created_by_id_users')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_asset_ownership_history_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_ownership_history'))
    )
    op.create_index(op.f('ix_asset_ownership_history_asset_id'), 'asset_ownership_history', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_ownership_history_organization_id'), 'asset_ownership_history', ['organization_id'], unique=False)
    
    # Create asset_media table
    op.create_table('asset_media',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('media_type', sa.String(length=20), server_default='PHOTO', nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_media_asset_id_assets')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_asset_media_organization_id_organizations')),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_asset_media_uploaded_by_id_users')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_asset_media_created_by_id_users')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_asset_media_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_media'))
    )
    op.create_index('uq_asset_primary_media', 'asset_media', ['organization_id', 'asset_id'], unique=True, postgresql_where=sa.text("is_primary AND is_active"))
    op.create_index(op.f('ix_asset_media_asset_id'), 'asset_media', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_media_organization_id'), 'asset_media', ['organization_id'], unique=False)
    
    # Create asset_inspections table
    op.create_table('asset_inspections',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('inspection_type', sa.String(length=40), nullable=False),
    sa.Column('inspection_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('inspected_by_id', sa.Uuid(), nullable=False),
    sa.Column('meter_reading', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('condition_status', sa.String(length=30), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('defects_found', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('defect_notes', sa.Text(), nullable=True),
    sa.Column('follow_up_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_inspections_asset_id_assets')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_asset_inspections_organization_id_organizations')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_asset_inspections_project_id_projects')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_asset_inspections_location_id_locations')),
    sa.ForeignKeyConstraint(['inspected_by_id'], ['users.id'], name=op.f('fk_asset_inspections_inspected_by_id_users')),
    sa.ForeignKeyConstraint(['document_id'], ['asset_documents.id'], name=op.f('fk_asset_inspections_document_id_asset_documents')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_asset_inspections_created_by_id_users')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_asset_inspections_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_inspections'))
    )
    op.create_index('ix_inspection_date', 'asset_inspections', ['organization_id', 'asset_id', 'inspection_date'], unique=False)
    op.create_index(op.f('ix_asset_inspections_asset_id'), 'asset_inspections', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_inspections_organization_id'), 'asset_inspections', ['organization_id'], unique=False)
    
    # Create asset_defects table
    op.create_table('asset_defects',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('inspection_id', sa.Uuid(), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reported_by_id', sa.Uuid(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='OPEN', nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_defects_asset_id_assets')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_asset_defects_organization_id_organizations')),
    sa.ForeignKeyConstraint(['inspection_id'], ['asset_inspections.id'], name=op.f('fk_asset_defects_inspection_id_asset_inspections')),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], name=op.f('fk_asset_defects_reported_by_id_users')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_asset_defects_created_by_id_users')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_asset_defects_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_defects'))
    )
    op.create_index('ix_asset_defect_state', 'asset_defects', ['organization_id', 'asset_id', 'status', 'severity'], unique=False)
    op.create_index(op.f('ix_asset_defects_asset_id'), 'asset_defects', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_defects_organization_id'), 'asset_defects', ['organization_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_asset_defect_state', table_name='asset_defects')
    op.drop_index(op.f('ix_asset_defects_organization_id'), table_name='asset_defects')
    op.drop_index(op.f('ix_asset_defects_asset_id'), table_name='asset_defects')
    op.drop_table('asset_defects')
    
    op.drop_index('ix_inspection_date', table_name='asset_inspections')
    op.drop_index(op.f('ix_asset_inspections_organization_id'), table_name='asset_inspections')
    op.drop_index(op.f('ix_asset_inspections_asset_id'), table_name='asset_inspections')
    op.drop_table('asset_inspections')
    
    op.drop_index('uq_asset_primary_media', table_name='asset_media')
    op.drop_index(op.f('ix_asset_media_organization_id'), table_name='asset_media')
    op.drop_index(op.f('ix_asset_media_asset_id'), table_name='asset_media')
    op.drop_table('asset_media')
    
    op.drop_index(op.f('ix_asset_ownership_history_organization_id'), table_name='asset_ownership_history')
    op.drop_index(op.f('ix_asset_ownership_history_asset_id'), table_name='asset_ownership_history')
    op.drop_table('asset_ownership_history')
    
    op.drop_index('ix_registration_expiry', table_name='asset_registrations')
    op.drop_index(op.f('ix_asset_registrations_organization_id'), table_name='asset_registrations')
    op.drop_index(op.f('ix_asset_registrations_asset_id'), table_name='asset_registrations')
    op.drop_table('asset_registrations')
    
    op.drop_index('ix_insurance_expiry', table_name='asset_insurance_records')
    op.drop_index(op.f('ix_asset_insurance_records_organization_id'), table_name='asset_insurance_records')
    op.drop_index(op.f('ix_asset_insurance_records_asset_id'), table_name='asset_insurance_records')
    op.drop_table('asset_insurance_records')
    
    op.drop_index('ix_asset_status_time', table_name='asset_status_history')
    op.drop_index(op.f('ix_asset_status_history_organization_id'), table_name='asset_status_history')
    op.drop_index(op.f('ix_asset_status_history_asset_id'), table_name='asset_status_history')
    op.drop_table('asset_status_history')
    
    op.drop_index('ix_asset_location_time', table_name='asset_location_history')
    op.drop_index(op.f('ix_asset_location_history_organization_id'), table_name='asset_location_history')
    op.drop_index(op.f('ix_asset_location_history_asset_id'), table_name='asset_location_history')
    op.drop_table('asset_location_history')
    
    op.drop_constraint(op.f('fk_asset_assignments_primary_operator_id_employees'), 'asset_assignments', type_='foreignkey')
    op.drop_column('asset_assignments', 'expected_return_at')
    op.drop_column('asset_assignments', 'primary_operator_id')
    op.drop_column('asset_assignments', 'assignment_reason')
    
    op.execute("ALTER TYPE ownership_type RENAME TO ownership_type_old")
    sa.Enum('OWNED', 'LEASED', 'RENTED', 'CLIENT_OWNED', 'OTHER', name='ownership_type').create(op.get_bind())
    op.execute("ALTER TABLE assets ALTER COLUMN ownership_type TYPE ownership_type USING ownership_type::text::ownership_type")
    op.execute("DROP TYPE ownership_type_old")
    
    op.execute("ALTER TYPE meter_type RENAME TO meter_type_old")
    sa.Enum('ENGINE_HOURS', 'OPERATING_HOURS', 'ODOMETER_KM', 'NONE', name='meter_type').create(op.get_bind())
    op.execute("ALTER TABLE assets ALTER COLUMN meter_type TYPE meter_type USING meter_type::text::meter_type")
    op.execute("ALTER TABLE asset_categories ALTER COLUMN default_meter_type TYPE meter_type USING default_meter_type::text::meter_type")
    op.execute("DROP TYPE meter_type_old")
    
    op.execute("ALTER TYPE asset_status RENAME TO asset_status_old")
    sa.Enum('AVAILABLE', 'OPERATING', 'MOBILIZING', 'STANDBY', 'UNDER_MAINTENANCE', 'BREAKDOWN', 'OUT_OF_SERVICE', 'DISPOSED', name='asset_status').create(op.get_bind())
    op.execute("ALTER TABLE assets ALTER COLUMN status TYPE asset_status USING status::text::asset_status")
    op.execute("DROP TYPE asset_status_old")
    
    op.drop_constraint(op.f('fk_assets_primary_operator_id_employees'), 'assets', type_='foreignkey')
    op.drop_index('ix_assets_org_operator', table_name='assets')
    op.drop_index('ix_assets_org_serial', table_name='assets')
    op.drop_index('ix_assets_org_registration', table_name='assets')
    op.drop_index(op.f('ix_assets_primary_operator'), table_name='assets')
    op.drop_column('assets', 'barcode_value')
    op.drop_column('assets', 'qr_code_value')
    op.drop_column('assets', 'profile_photo_url')
    op.drop_column('assets', 'primary_operator_id')
    op.drop_column('assets', 'residual_value')
    op.drop_column('assets', 'expected_service_life_years')
    op.drop_column('assets', 'warranty_start_date')
    op.drop_column('assets', 'supplier_id')
    op.drop_column('assets', 'commission_date')
    op.drop_column('assets', 'purchase_currency')
    op.drop_column('assets', 'ownership_entity')
    op.drop_column('assets', 'vin')
    op.drop_column('assets', 'chassis_number')
    op.drop_column('assets', 'engine_model')
    op.drop_column('assets', 'engine_manufacturer')
    
    op.drop_constraint(op.f('fk_asset_categories_updated_by_id_users'), 'asset_categories', type_='foreignkey')
    op.drop_constraint(op.f('fk_asset_categories_created_by_id_users'), 'asset_categories', type_='foreignkey')
    op.drop_column('asset_categories', 'updated_by_id')
    op.drop_column('asset_categories', 'created_by_id')
    op.drop_column('asset_categories', 'requires_operator')
    op.drop_column('asset_categories', 'requires_insurance')
    op.drop_column('asset_categories', 'requires_registration')
    op.drop_column('asset_categories', 'is_mobile')
    op.drop_column('asset_categories', 'default_meter_type')
    op.drop_column('asset_categories', 'code')
    
    # ### end Alembic commands ###
