"""add leave_type to leave_requests

Revision ID: 17f0842562e9
Revises: 20260914_assistant_chat_messages
"""
from alembic import op
import sqlalchemy as sa


revision = '17f0842562e9'
down_revision = '20260914_assistant_chat_messages'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_asset_fuel_reductions_organization_id'), 'asset_fuel_reductions', ['organization_id'], unique=False)
    op.drop_constraint(op.f('fk_asset_fuel_reductions_fuel_log_id'), 'asset_fuel_reductions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_asset_fuel_reductions_fuel_log_id_asset_fuel_logs'), 'asset_fuel_reductions', 'asset_fuel_logs', ['fuel_log_id'], ['id'])
    op.create_index(op.f('ix_asset_log_files_organization_id'), 'asset_log_files', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_assets_primary_operator'), table_name='assets')
    op.create_index(op.f('ix_assistant_chat_messages_organization_id'), 'assistant_chat_messages', ['organization_id'], unique=False)
    op.create_index(op.f('ix_fuel_suppliers_organization_id'), 'fuel_suppliers', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_library_text'), table_name='library_documents', postgresql_using='gin')
    op.create_index(op.f('ix_notification_schedules_organization_id'), 'notification_schedules', ['organization_id'], unique=False)
    op.alter_column('notifications', 'rule_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('notifications', 'document_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('notifications', 'expiry_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('notifications', 'message',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.add_column('suppliers', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('suppliers', sa.Column('country', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'country')
    op.drop_column('suppliers', 'address')
    op.alter_column('notifications', 'message',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('notifications', 'expiry_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('notifications', 'document_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('notifications', 'rule_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_notification_schedules_organization_id'), table_name='notification_schedules')
    op.create_index(op.f('ix_library_text'), 'library_documents', [sa.literal_column("to_tsvector('simple'::regconfig, extracted_text)")], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_fuel_suppliers_organization_id'), table_name='fuel_suppliers')
    op.drop_index(op.f('ix_assistant_chat_messages_organization_id'), table_name='assistant_chat_messages')
    op.create_index(op.f('ix_assets_primary_operator'), 'assets', ['primary_operator_id'], unique=False)
    op.drop_index(op.f('ix_asset_log_files_organization_id'), table_name='asset_log_files')
    op.drop_constraint(op.f('fk_asset_fuel_reductions_fuel_log_id_asset_fuel_logs'), 'asset_fuel_reductions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_asset_fuel_reductions_fuel_log_id'), 'asset_fuel_reductions', 'asset_fuel_logs', ['fuel_log_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_asset_fuel_reductions_organization_id'), table_name='asset_fuel_reductions')
    # ### end Alembic commands ###
