"""HR salaries contract reminders employee accounts

Revision ID: 19b94659bc6a
Revises: 13156ff3fcde
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '19b94659bc6a'
down_revision = '8f2a3b5c6d7e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_alert_rules',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=True),
    sa.Column('lead_value', sa.Integer(), nullable=False),
    sa.Column('lead_unit', sa.String(length=10), nullable=False),
    sa.Column('recipient_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_contract_alert_rules_employee_id_employees')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_contract_alert_rules_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contract_alert_rules'))
    )
    op.create_index(op.f('ix_contract_alert_rules_organization_id'), 'contract_alert_rules', ['organization_id'], unique=False)
    op.create_table('email_deliveries',
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_email_deliveries_organization_id_organizations')),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('fk_email_deliveries_recipient_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_deliveries'))
    )
    op.create_index(op.f('ix_email_deliveries_organization_id'), 'email_deliveries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_email_deliveries_recipient_id'), 'email_deliveries', ['recipient_id'], unique=False)
    op.create_table('employee_salaries',
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('pay_period', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_employee_salaries_salary_nonnegative')),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name=op.f('ck_employee_salaries_salary_dates')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_employee_salaries_created_by_id_users')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_salaries_employee_id_employees')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_employee_salaries_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_salaries'))
    )
    op.create_index(op.f('ix_employee_salaries_employee_id'), 'employee_salaries', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_salaries_organization_id'), 'employee_salaries', ['organization_id'], unique=False)
    op.create_table('password_setups',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_password_setups_organization_id_organizations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_setups_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_setups')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_password_setups_token_hash'))
    )
    op.create_index(op.f('ix_password_setups_organization_id'), 'password_setups', ['organization_id'], unique=False)
    op.create_index(op.f('ix_password_setups_user_id'), 'password_setups', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['employee_documents.id'], name=op.f('fk_notifications_document_id_employee_documents')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_notifications_organization_id_organizations')),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('fk_notifications_recipient_id_users')),
    sa.ForeignKeyConstraint(['rule_id'], ['contract_alert_rules.id'], name=op.f('fk_notifications_rule_id_contract_alert_rules')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('rule_id', 'document_id', 'expiry_date', 'recipient_id', name=op.f('uq_notifications_rule_id'))
    )
    op.create_index(op.f('ix_notifications_organization_id'), 'notifications', ['organization_id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.add_column('employees', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint(op.f('uq_employees_user_id'), 'employees', ['user_id'])
    op.create_foreign_key(op.f('fk_employees_user_id_users'), 'employees', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('token_version', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('setup_required', sa.Boolean(), server_default='false', nullable=False))
    # Introduce explicit HR grants for established administrative/HR/finance roles.
    for code in ("employees.salary.read", "employees.salary.manage", "employees.alerts.manage"):
        op.execute(sa.text("INSERT INTO permissions (id, code) VALUES (gen_random_uuid(), :code) ON CONFLICT (code) DO NOTHING").bindparams(code=code))
        names = ("Administrator", "CEO", "HR") if code == "employees.alerts.manage" else ("Administrator", "CEO", "HR", "Finance")
        for name in names:
            op.execute(sa.text("INSERT INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r CROSS JOIN permissions p WHERE r.name = :name AND p.code = :code ON CONFLICT DO NOTHING").bindparams(name=name, code=code))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'setup_required')
    op.drop_column('users', 'token_version')
    op.drop_constraint(op.f('fk_employees_user_id_users'), 'employees', type_='foreignkey')
    op.drop_constraint(op.f('uq_employees_user_id'), 'employees', type_='unique')
    op.drop_column('employees', 'user_id')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_organization_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_password_setups_user_id'), table_name='password_setups')
    op.drop_index(op.f('ix_password_setups_organization_id'), table_name='password_setups')
    op.drop_table('password_setups')
    op.drop_index(op.f('ix_employee_salaries_organization_id'), table_name='employee_salaries')
    op.drop_index(op.f('ix_employee_salaries_employee_id'), table_name='employee_salaries')
    op.drop_table('employee_salaries')
    op.drop_index(op.f('ix_email_deliveries_recipient_id'), table_name='email_deliveries')
    op.drop_index(op.f('ix_email_deliveries_organization_id'), table_name='email_deliveries')
    op.drop_table('email_deliveries')
    op.drop_index(op.f('ix_contract_alert_rules_organization_id'), table_name='contract_alert_rules')
    op.drop_table('contract_alert_rules')
    # ### end Alembic commands ###
