"""Add template-driven preventive maintenance job cards."""
from alembic import op
import sqlalchemy as sa
revision = "20260922_pm_job_cards"
down_revision = "20260922_fuel_deliveries"
branch_labels = None
depends_on = None
def common(prefix):
    return [sa.Column("id", sa.Uuid(), primary_key=True), sa.Column("organization_id", sa.Uuid(), sa.ForeignKey("organizations.id"), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.Column("created_by_id", sa.Uuid(), sa.ForeignKey("users.id")), sa.Column("updated_by_id", sa.Uuid(), sa.ForeignKey("users.id")), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("archived_at", sa.DateTime(timezone=True))]
def upgrade():
    op.create_table("pm_templates", *common("pm"), sa.Column("name", sa.String(200), nullable=False), sa.Column("equipment_type", sa.String(100)), sa.Column("pm_interval", sa.String(100), nullable=False), sa.Column("inspection_items", sa.JSON(), nullable=False, server_default="[]"))
    op.create_table("pm_job_cards", *common("pm"), sa.Column("job_card_number", sa.String(50), nullable=False, unique=True), sa.Column("project_id", sa.Uuid(), sa.ForeignKey("projects.id")), sa.Column("site_location_id", sa.Uuid(), sa.ForeignKey("locations.id")), sa.Column("asset_id", sa.Uuid(), sa.ForeignKey("assets.id"), nullable=False), sa.Column("template_id", sa.Uuid(), sa.ForeignKey("pm_templates.id")), sa.Column("status", sa.String(30), nullable=False, server_default="DRAFT"), sa.Column("pm_control", sa.JSON(), nullable=False, server_default="{}"), sa.Column("inspection_items", sa.JSON(), nullable=False, server_default="[]"), sa.Column("service_defect_control", sa.JSON(), nullable=False, server_default="{}"), sa.Column("machine_release", sa.JSON(), nullable=False, server_default="{}"), sa.Column("technicians", sa.JSON(), nullable=False, server_default="[]"), sa.Column("signatures", sa.JSON(), nullable=False, server_default="{}"), sa.Column("supervisor_comments", sa.Text()), sa.Column("submitted_at", sa.DateTime(timezone=True)), sa.Column("completed_at", sa.DateTime(timezone=True)))
    op.add_column("pm_job_cards", sa.Column("work_order_id", sa.Uuid(), sa.ForeignKey("maintenance_work_orders.id")))
    op.create_table("breakdown_job_cards", *common("breakdown"), sa.Column("job_card_number", sa.String(50), nullable=False, unique=True), sa.Column("project_id", sa.Uuid(), sa.ForeignKey("projects.id")), sa.Column("site_location_id", sa.Uuid(), sa.ForeignKey("locations.id")), sa.Column("asset_id", sa.Uuid(), sa.ForeignKey("assets.id"), nullable=False), sa.Column("work_order_id", sa.Uuid(), sa.ForeignKey("maintenance_work_orders.id")), sa.Column("status", sa.String(30), nullable=False, server_default="DRAFT"), sa.Column("job_control", sa.JSON(), nullable=False, server_default="{}"), sa.Column("reported_failure", sa.Text()), sa.Column("corrective_action", sa.Text()), sa.Column("parts_materials", sa.JSON(), nullable=False, server_default="[]"), sa.Column("labour_downtime", sa.JSON(), nullable=False, server_default="[]"), sa.Column("test_release", sa.JSON(), nullable=False, server_default="{}"), sa.Column("signatures", sa.JSON(), nullable=False, server_default="{}"))
def downgrade():
    op.drop_table("breakdown_job_cards"); op.drop_table("pm_job_cards"); op.drop_table("pm_templates")
