"""migrate client country to string 100 for full name

Revision ID: 7a0ebcb0e5cf
Revises: 20261013_employee_timesheets
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '7a0ebcb0e5cf'
down_revision = '20261013_employee_timesheets'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_action_trackers_archived_at'), 'action_trackers', ['archived_at'], unique=False)
    op.create_index(op.f('ix_action_trackers_organization_id'), 'action_trackers', ['organization_id'], unique=False)
    op.create_index(op.f('ix_asset_fuel_reductions_organization_id'), 'asset_fuel_reductions', ['organization_id'], unique=False)
    op.drop_constraint(op.f('fk_asset_fuel_reductions_fuel_log_id'), 'asset_fuel_reductions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_asset_fuel_reductions_fuel_log_id_asset_fuel_logs'), 'asset_fuel_reductions', 'asset_fuel_logs', ['fuel_log_id'], ['id'])
    op.create_index(op.f('ix_asset_log_files_organization_id'), 'asset_log_files', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_assets_primary_operator'), table_name='assets')
    op.create_index(op.f('ix_assistant_chat_messages_organization_id'), 'assistant_chat_messages', ['organization_id'], unique=False)
    op.create_index(op.f('ix_breakdown_job_cards_archived_at'), 'breakdown_job_cards', ['archived_at'], unique=False)
    op.create_index(op.f('ix_client_project_grants_client_id'), 'client_project_grants', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_project_grants_organization_id'), 'client_project_grants', ['organization_id'], unique=False)
    op.create_index(op.f('ix_client_project_grants_project_id'), 'client_project_grants', ['project_id'], unique=False)
    op.alter_column('client_published_artifacts', 'artifact_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('SHIFT_REPORT', 'HOLE_LOG', 'PROGRESS_SUMMARY', 'PHOTO', 'INVOICE_STATEMENT', name='client_artifact_type', native_enum=False),
               existing_nullable=False)
    op.create_index(op.f('ix_client_published_artifacts_client_id'), 'client_published_artifacts', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_published_artifacts_organization_id'), 'client_published_artifacts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_client_published_artifacts_project_id'), 'client_published_artifacts', ['project_id'], unique=False)
    op.alter_column('commercial_opportunities', 'tender_stage',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PROSPECT', 'QUALIFIED', 'PROPOSAL_SENT', 'NEGOTIATION', 'WON', 'LOST', name='tender_stage', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'PROSPECT'::character varying"))
    op.create_index(op.f('ix_commercial_opportunities_archived_at'), 'commercial_opportunities', ['archived_at'], unique=False)
    op.create_index(op.f('ix_commercial_opportunities_client_id'), 'commercial_opportunities', ['client_id'], unique=False)
    op.create_index(op.f('ix_commercial_opportunities_organization_id'), 'commercial_opportunities', ['organization_id'], unique=False)
    op.alter_column('contract_rate_cards', 'rate_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('DRILLING_METER', 'STANDBY_HOURLY', 'MOBILIZATION_FLAT', 'DEMOBILIZATION_FLAT', 'DAYWORK_HOURLY', name='rate_type', native_enum=False),
               existing_nullable=False)
    op.create_index(op.f('ix_contract_rate_cards_contract_id'), 'contract_rate_cards', ['contract_id'], unique=False)
    op.create_index(op.f('ix_contract_rate_cards_organization_id'), 'contract_rate_cards', ['organization_id'], unique=False)
    op.alter_column('cost_subledger_entries', 'cost_category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('LABOUR', 'FUEL', 'MAINTENANCE_PARTS', 'CONSUMABLES', 'LOGISTICS', 'CAMP', 'SUBCONTRACTOR', 'OVERHEAD', name='cost_category', native_enum=False),
               existing_nullable=False)
    op.create_index(op.f('ix_cost_subledger_entries_organization_id'), 'cost_subledger_entries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_cost_subledger_entries_project_id'), 'cost_subledger_entries', ['project_id'], unique=False)
    op.create_index(op.f('ix_cost_subledger_entries_rig_id'), 'cost_subledger_entries', ['rig_id'], unique=False)
    op.create_index(op.f('ix_cost_subledger_entries_shift_report_id'), 'cost_subledger_entries', ['shift_report_id'], unique=False)
    op.alter_column('drill_holes', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='drill_hole_status', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'PLANNED'::character varying"))
    op.create_index(op.f('ix_drill_holes_archived_at'), 'drill_holes', ['archived_at'], unique=False)
    op.create_index(op.f('ix_drill_holes_organization_id'), 'drill_holes', ['organization_id'], unique=False)
    op.create_index(op.f('ix_drill_holes_program_id'), 'drill_holes', ['program_id'], unique=False)
    op.create_index(op.f('ix_drill_holes_project_id'), 'drill_holes', ['project_id'], unique=False)
    op.alter_column('drilling_programs', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('PLANNING', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='drilling_program_status', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'PLANNING'::character varying"))
    op.create_index(op.f('ix_drilling_programs_archived_at'), 'drilling_programs', ['archived_at'], unique=False)
    op.create_index(op.f('ix_drilling_programs_organization_id'), 'drilling_programs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_drilling_programs_project_id'), 'drilling_programs', ['project_id'], unique=False)
    op.create_index(op.f('ix_drilling_shift_crews_employee_id'), 'drilling_shift_crews', ['employee_id'], unique=False)
    op.create_index(op.f('ix_drilling_shift_crews_organization_id'), 'drilling_shift_crews', ['organization_id'], unique=False)
    op.create_index(op.f('ix_drilling_shift_crews_shift_report_id'), 'drilling_shift_crews', ['shift_report_id'], unique=False)
    op.create_index(op.f('ix_drilling_shift_intervals_drill_hole_id'), 'drilling_shift_intervals', ['drill_hole_id'], unique=False)
    op.create_index(op.f('ix_drilling_shift_intervals_organization_id'), 'drilling_shift_intervals', ['organization_id'], unique=False)
    op.create_index(op.f('ix_drilling_shift_intervals_shift_report_id'), 'drilling_shift_intervals', ['shift_report_id'], unique=False)
    op.alter_column('drilling_shift_reports', 'shift_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('DAY', 'NIGHT', name='shift_type', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'DAY'::character varying"))
    op.alter_column('drilling_shift_reports', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'RETURNED', name='shift_report_status', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'DRAFT'::character varying"))
    op.create_index(op.f('ix_drilling_shift_reports_archived_at'), 'drilling_shift_reports', ['archived_at'], unique=False)
    op.create_index(op.f('ix_drilling_shift_reports_date'), 'drilling_shift_reports', ['date'], unique=False)
    op.create_index(op.f('ix_drilling_shift_reports_organization_id'), 'drilling_shift_reports', ['organization_id'], unique=False)
    op.create_index(op.f('ix_drilling_shift_reports_program_id'), 'drilling_shift_reports', ['program_id'], unique=False)
    op.create_index(op.f('ix_drilling_shift_reports_project_id'), 'drilling_shift_reports', ['project_id'], unique=False)
    op.create_index(op.f('ix_drilling_shift_reports_rig_id'), 'drilling_shift_reports', ['rig_id'], unique=False)
    op.create_index(op.f('ix_drilling_shift_reports_status'), 'drilling_shift_reports', ['status'], unique=False)
    op.alter_column('drilling_shift_time_segments', 'category',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('PRODUCTIVE', 'STANDBY', 'MAINTENANCE', 'NON_PRODUCTIVE', name='time_category', native_enum=False),
               existing_nullable=False)
    op.create_index(op.f('ix_drilling_shift_time_segments_organization_id'), 'drilling_shift_time_segments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_drilling_shift_time_segments_shift_report_id'), 'drilling_shift_time_segments', ['shift_report_id'], unique=False)
    op.create_index(op.f('ix_equipment_register_entries_archived_at'), 'equipment_register_entries', ['archived_at'], unique=False)
    op.create_index(op.f('ix_equipment_register_entries_organization_id'), 'equipment_register_entries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_fuel_allocations_archived_at'), 'fuel_allocations', ['archived_at'], unique=False)
    op.create_index(op.f('ix_fuel_allocations_organization_id'), 'fuel_allocations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_fuel_deliveries_archived_at'), 'fuel_deliveries', ['archived_at'], unique=False)
    op.create_index(op.f('ix_fuel_deliveries_organization_id'), 'fuel_deliveries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_fuel_suppliers_organization_id'), 'fuel_suppliers', ['organization_id'], unique=False)
    op.alter_column('hse_corrective_actions', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('OPEN', 'IN_PROGRESS', 'UNDER_REVIEW', 'CLOSED', name='hse_action_status', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'OPEN'::character varying"))
    op.create_index(op.f('ix_hse_corrective_actions_assigned_to_id'), 'hse_corrective_actions', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_hse_corrective_actions_incident_id'), 'hse_corrective_actions', ['incident_id'], unique=False)
    op.create_index(op.f('ix_hse_corrective_actions_organization_id'), 'hse_corrective_actions', ['organization_id'], unique=False)
    op.alter_column('hse_incidents', 'incident_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('NEAR_MISS', 'FIRST_AID', 'MEDICAL_TREATMENT', 'LOST_TIME_INJURY', 'ENVIRONMENTAL_SPILL', 'PROPERTY_DAMAGE', 'FATALITY', name='hse_incident_type', native_enum=False),
               existing_nullable=False)
    op.alter_column('hse_incidents', 'severity',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='hse_severity', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'MEDIUM'::character varying"))
    op.alter_column('hse_incidents', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('REPORTED', 'UNDER_INVESTIGATION', 'CORRECTIVE_ACTION_PENDING', 'CLOSED', name='hse_incident_status', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'REPORTED'::character varying"))
    op.create_index(op.f('ix_hse_incidents_archived_at'), 'hse_incidents', ['archived_at'], unique=False)
    op.create_index(op.f('ix_hse_incidents_organization_id'), 'hse_incidents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_hse_incidents_project_id'), 'hse_incidents', ['project_id'], unique=False)
    op.drop_index(op.f('ix_library_text'), table_name='library_documents', postgresql_using='gin')
    op.alter_column('maintenance_work_orders', 'work_type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('PREVENTIVE', 'CORRECTIVE', 'EMERGENCY', 'OVERHAUL', name='wo_type', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'CORRECTIVE'::character varying"))
    op.alter_column('maintenance_work_orders', 'priority',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='wo_priority', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'MEDIUM'::character varying"))
    op.alter_column('maintenance_work_orders', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('OPEN', 'IN_PROGRESS', 'WAITING_PARTS', 'COMPLETED', 'CANCELLED', name='wo_status', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'OPEN'::character varying"))
    op.alter_column('maintenance_work_orders', 'failure_taxonomy',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('MECHANICAL', 'HYDRAULIC', 'ELECTRICAL', 'ENGINE', 'STRUCTURAL', 'TYRES_TRACKS', 'OPERATOR_ERROR', name='failure_taxonomy', native_enum=False),
               existing_nullable=True)
    op.create_index(op.f('ix_maintenance_work_orders_archived_at'), 'maintenance_work_orders', ['archived_at'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_asset_id'), 'maintenance_work_orders', ['asset_id'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_defect_id'), 'maintenance_work_orders', ['defect_id'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_inspection_id'), 'maintenance_work_orders', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_organization_id'), 'maintenance_work_orders', ['organization_id'], unique=False)
    op.create_index(op.f('ix_maintenance_work_orders_project_id'), 'maintenance_work_orders', ['project_id'], unique=False)
    op.create_index(op.f('ix_notification_schedules_organization_id'), 'notification_schedules', ['organization_id'], unique=False)
    op.create_index(op.f('ix_operational_expense_payments_organization_id'), 'operational_expense_payments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_operational_expenses_organization_id'), 'operational_expenses', ['organization_id'], unique=False)
    op.drop_column('operational_expenses', 'is_active')
    op.drop_column('operational_expenses', 'archived_at')
    op.create_index(op.f('ix_operational_payees_organization_id'), 'operational_payees', ['organization_id'], unique=False)
    op.drop_column('operational_payees', 'archived_at')
    op.create_index(op.f('ix_pm_job_cards_archived_at'), 'pm_job_cards', ['archived_at'], unique=False)
    op.create_index(op.f('ix_pm_job_cards_organization_id'), 'pm_job_cards', ['organization_id'], unique=False)
    op.create_index(op.f('ix_pm_templates_organization_id'), 'pm_templates', ['organization_id'], unique=False)
    op.drop_column('pm_templates', 'archived_at')
    op.create_index(op.f('ix_pm_trackers_archived_at'), 'pm_trackers', ['archived_at'], unique=False)
    op.create_index(op.f('ix_pm_trackers_organization_id'), 'pm_trackers', ['organization_id'], unique=False)
    op.alter_column('project_contracts', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('DRAFT', 'ACTIVE', 'EXPIRED', 'SUPERSEDED', name='contract_status', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.create_index(op.f('ix_project_contracts_archived_at'), 'project_contracts', ['archived_at'], unique=False)
    op.create_index(op.f('ix_project_contracts_organization_id'), 'project_contracts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_project_contracts_project_id'), 'project_contracts', ['project_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_items_organization_id'), 'purchase_order_items', ['organization_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_items_purchase_order_id'), 'purchase_order_items', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_archived_at'), 'purchase_orders', ['archived_at'], unique=False)
    op.create_index(op.f('ix_purchase_orders_organization_id'), 'purchase_orders', ['organization_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_project_id'), 'purchase_orders', ['project_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_request_id'), 'purchase_orders', ['request_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False)
    op.alter_column('revenue_subledger_entries', 'revenue_category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('DRILLING_METERAGE', 'STANDBY_TIME', 'MOBILIZATION', 'DAYWORK', 'REIMBURSABLE', name='revenue_category', native_enum=False),
               existing_nullable=False)
    op.create_index(op.f('ix_revenue_subledger_entries_contract_id'), 'revenue_subledger_entries', ['contract_id'], unique=False)
    op.create_index(op.f('ix_revenue_subledger_entries_organization_id'), 'revenue_subledger_entries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_revenue_subledger_entries_project_id'), 'revenue_subledger_entries', ['project_id'], unique=False)
    op.create_index(op.f('ix_revenue_subledger_entries_rate_card_id'), 'revenue_subledger_entries', ['rate_card_id'], unique=False)
    op.create_index(op.f('ix_revenue_subledger_entries_rig_id'), 'revenue_subledger_entries', ['rig_id'], unique=False)
    op.create_index(op.f('ix_revenue_subledger_entries_shift_report_id'), 'revenue_subledger_entries', ['shift_report_id'], unique=False)
    op.create_index(op.f('ix_supervisor_scorecards_archived_at'), 'supervisor_scorecards', ['archived_at'], unique=False)
    op.create_index(op.f('ix_supervisor_scorecards_organization_id'), 'supervisor_scorecards', ['organization_id'], unique=False)
    op.create_index(op.f('ix_supervisor_scorecards_project_id'), 'supervisor_scorecards', ['project_id'], unique=False)
    op.create_index(op.f('ix_supervisor_scorecards_supervisor_id'), 'supervisor_scorecards', ['supervisor_id'], unique=False)
    op.alter_column('clients', 'country',
               existing_type=sa.String(length=2),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.add_column('suppliers', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('suppliers', sa.Column('country', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_work_order_cost_lines_organization_id'), 'work_order_cost_lines', ['organization_id'], unique=False)
    op.create_index(op.f('ix_work_order_cost_lines_work_order_id'), 'work_order_cost_lines', ['work_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_order_cost_lines_work_order_id'), table_name='work_order_cost_lines')
    op.drop_index(op.f('ix_work_order_cost_lines_organization_id'), table_name='work_order_cost_lines')
    op.drop_column('suppliers', 'country')
    op.drop_column('suppliers', 'address')
    op.drop_index(op.f('ix_supervisor_scorecards_supervisor_id'), table_name='supervisor_scorecards')
    op.drop_index(op.f('ix_supervisor_scorecards_project_id'), table_name='supervisor_scorecards')
    op.drop_index(op.f('ix_supervisor_scorecards_organization_id'), table_name='supervisor_scorecards')
    op.drop_index(op.f('ix_supervisor_scorecards_archived_at'), table_name='supervisor_scorecards')
    op.drop_index(op.f('ix_revenue_subledger_entries_shift_report_id'), table_name='revenue_subledger_entries')
    op.drop_index(op.f('ix_revenue_subledger_entries_rig_id'), table_name='revenue_subledger_entries')
    op.drop_index(op.f('ix_revenue_subledger_entries_rate_card_id'), table_name='revenue_subledger_entries')
    op.drop_index(op.f('ix_revenue_subledger_entries_project_id'), table_name='revenue_subledger_entries')
    op.drop_index(op.f('ix_revenue_subledger_entries_organization_id'), table_name='revenue_subledger_entries')
    op.drop_index(op.f('ix_revenue_subledger_entries_contract_id'), table_name='revenue_subledger_entries')
    op.alter_column('revenue_subledger_entries', 'revenue_category',
               existing_type=sa.Enum('DRILLING_METERAGE', 'STANDBY_TIME', 'MOBILIZATION', 'DAYWORK', 'REIMBURSABLE', name='revenue_category', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_purchase_orders_supplier_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_request_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_project_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_organization_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_archived_at'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_order_items_purchase_order_id'), table_name='purchase_order_items')
    op.drop_index(op.f('ix_purchase_order_items_organization_id'), table_name='purchase_order_items')
    op.drop_index(op.f('ix_project_contracts_project_id'), table_name='project_contracts')
    op.drop_index(op.f('ix_project_contracts_organization_id'), table_name='project_contracts')
    op.drop_index(op.f('ix_project_contracts_archived_at'), table_name='project_contracts')
    op.alter_column('project_contracts', 'status',
               existing_type=sa.Enum('DRAFT', 'ACTIVE', 'EXPIRED', 'SUPERSEDED', name='contract_status', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.drop_index(op.f('ix_pm_trackers_organization_id'), table_name='pm_trackers')
    op.drop_index(op.f('ix_pm_trackers_archived_at'), table_name='pm_trackers')
    op.add_column('pm_templates', sa.Column('archived_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_pm_templates_organization_id'), table_name='pm_templates')
    op.drop_index(op.f('ix_pm_job_cards_organization_id'), table_name='pm_job_cards')
    op.drop_index(op.f('ix_pm_job_cards_archived_at'), table_name='pm_job_cards')
    op.add_column('operational_payees', sa.Column('archived_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_operational_payees_organization_id'), table_name='operational_payees')
    op.add_column('operational_expenses', sa.Column('archived_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('operational_expenses', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_operational_expenses_organization_id'), table_name='operational_expenses')
    op.drop_index(op.f('ix_operational_expense_payments_organization_id'), table_name='operational_expense_payments')
    op.drop_index(op.f('ix_notification_schedules_organization_id'), table_name='notification_schedules')
    op.drop_index(op.f('ix_maintenance_work_orders_project_id'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_organization_id'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_inspection_id'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_defect_id'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_asset_id'), table_name='maintenance_work_orders')
    op.drop_index(op.f('ix_maintenance_work_orders_archived_at'), table_name='maintenance_work_orders')
    op.alter_column('maintenance_work_orders', 'failure_taxonomy',
               existing_type=sa.Enum('MECHANICAL', 'HYDRAULIC', 'ELECTRICAL', 'ENGINE', 'STRUCTURAL', 'TYRES_TRACKS', 'OPERATOR_ERROR', name='failure_taxonomy', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('maintenance_work_orders', 'status',
               existing_type=sa.Enum('OPEN', 'IN_PROGRESS', 'WAITING_PARTS', 'COMPLETED', 'CANCELLED', name='wo_status', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'OPEN'::character varying"))
    op.alter_column('maintenance_work_orders', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='wo_priority', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'MEDIUM'::character varying"))
    op.alter_column('maintenance_work_orders', 'work_type',
               existing_type=sa.Enum('PREVENTIVE', 'CORRECTIVE', 'EMERGENCY', 'OVERHAUL', name='wo_type', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'CORRECTIVE'::character varying"))
    op.create_index(op.f('ix_library_text'), 'library_documents', [sa.literal_column("to_tsvector('simple'::regconfig, extracted_text)")], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_hse_incidents_project_id'), table_name='hse_incidents')
    op.drop_index(op.f('ix_hse_incidents_organization_id'), table_name='hse_incidents')
    op.drop_index(op.f('ix_hse_incidents_archived_at'), table_name='hse_incidents')
    op.alter_column('hse_incidents', 'status',
               existing_type=sa.Enum('REPORTED', 'UNDER_INVESTIGATION', 'CORRECTIVE_ACTION_PENDING', 'CLOSED', name='hse_incident_status', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'REPORTED'::character varying"))
    op.alter_column('hse_incidents', 'severity',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='hse_severity', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'MEDIUM'::character varying"))
    op.alter_column('hse_incidents', 'incident_type',
               existing_type=sa.Enum('NEAR_MISS', 'FIRST_AID', 'MEDICAL_TREATMENT', 'LOST_TIME_INJURY', 'ENVIRONMENTAL_SPILL', 'PROPERTY_DAMAGE', 'FATALITY', name='hse_incident_type', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_hse_corrective_actions_organization_id'), table_name='hse_corrective_actions')
    op.drop_index(op.f('ix_hse_corrective_actions_incident_id'), table_name='hse_corrective_actions')
    op.drop_index(op.f('ix_hse_corrective_actions_assigned_to_id'), table_name='hse_corrective_actions')
    op.alter_column('hse_corrective_actions', 'status',
               existing_type=sa.Enum('OPEN', 'IN_PROGRESS', 'UNDER_REVIEW', 'CLOSED', name='hse_action_status', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'OPEN'::character varying"))
    op.drop_index(op.f('ix_fuel_suppliers_organization_id'), table_name='fuel_suppliers')
    op.drop_index(op.f('ix_fuel_deliveries_organization_id'), table_name='fuel_deliveries')
    op.drop_index(op.f('ix_fuel_deliveries_archived_at'), table_name='fuel_deliveries')
    op.drop_index(op.f('ix_fuel_allocations_organization_id'), table_name='fuel_allocations')
    op.drop_index(op.f('ix_fuel_allocations_archived_at'), table_name='fuel_allocations')
    op.drop_index(op.f('ix_equipment_register_entries_organization_id'), table_name='equipment_register_entries')
    op.drop_index(op.f('ix_equipment_register_entries_archived_at'), table_name='equipment_register_entries')
    op.drop_index(op.f('ix_drilling_shift_time_segments_shift_report_id'), table_name='drilling_shift_time_segments')
    op.drop_index(op.f('ix_drilling_shift_time_segments_organization_id'), table_name='drilling_shift_time_segments')
    op.alter_column('drilling_shift_time_segments', 'category',
               existing_type=sa.Enum('PRODUCTIVE', 'STANDBY', 'MAINTENANCE', 'NON_PRODUCTIVE', name='time_category', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_index(op.f('ix_drilling_shift_reports_status'), table_name='drilling_shift_reports')
    op.drop_index(op.f('ix_drilling_shift_reports_rig_id'), table_name='drilling_shift_reports')
    op.drop_index(op.f('ix_drilling_shift_reports_project_id'), table_name='drilling_shift_reports')
    op.drop_index(op.f('ix_drilling_shift_reports_program_id'), table_name='drilling_shift_reports')
    op.drop_index(op.f('ix_drilling_shift_reports_organization_id'), table_name='drilling_shift_reports')
    op.drop_index(op.f('ix_drilling_shift_reports_date'), table_name='drilling_shift_reports')
    op.drop_index(op.f('ix_drilling_shift_reports_archived_at'), table_name='drilling_shift_reports')
    op.alter_column('drilling_shift_reports', 'status',
               existing_type=sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'RETURNED', name='shift_report_status', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'DRAFT'::character varying"))
    op.alter_column('drilling_shift_reports', 'shift_type',
               existing_type=sa.Enum('DAY', 'NIGHT', name='shift_type', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'DAY'::character varying"))
    op.drop_index(op.f('ix_drilling_shift_intervals_shift_report_id'), table_name='drilling_shift_intervals')
    op.drop_index(op.f('ix_drilling_shift_intervals_organization_id'), table_name='drilling_shift_intervals')
    op.drop_index(op.f('ix_drilling_shift_intervals_drill_hole_id'), table_name='drilling_shift_intervals')
    op.drop_index(op.f('ix_drilling_shift_crews_shift_report_id'), table_name='drilling_shift_crews')
    op.drop_index(op.f('ix_drilling_shift_crews_organization_id'), table_name='drilling_shift_crews')
    op.drop_index(op.f('ix_drilling_shift_crews_employee_id'), table_name='drilling_shift_crews')
    op.drop_index(op.f('ix_drilling_programs_project_id'), table_name='drilling_programs')
    op.drop_index(op.f('ix_drilling_programs_organization_id'), table_name='drilling_programs')
    op.drop_index(op.f('ix_drilling_programs_archived_at'), table_name='drilling_programs')
    op.alter_column('drilling_programs', 'status',
               existing_type=sa.Enum('PLANNING', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='drilling_program_status', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'PLANNING'::character varying"))
    op.drop_index(op.f('ix_drill_holes_project_id'), table_name='drill_holes')
    op.drop_index(op.f('ix_drill_holes_program_id'), table_name='drill_holes')
    op.drop_index(op.f('ix_drill_holes_organization_id'), table_name='drill_holes')
    op.drop_index(op.f('ix_drill_holes_archived_at'), table_name='drill_holes')
    op.alter_column('drill_holes', 'status',
               existing_type=sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='drill_hole_status', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'PLANNED'::character varying"))
    op.drop_index(op.f('ix_cost_subledger_entries_shift_report_id'), table_name='cost_subledger_entries')
    op.drop_index(op.f('ix_cost_subledger_entries_rig_id'), table_name='cost_subledger_entries')
    op.drop_index(op.f('ix_cost_subledger_entries_project_id'), table_name='cost_subledger_entries')
    op.drop_index(op.f('ix_cost_subledger_entries_organization_id'), table_name='cost_subledger_entries')
    op.alter_column('cost_subledger_entries', 'cost_category',
               existing_type=sa.Enum('LABOUR', 'FUEL', 'MAINTENANCE_PARTS', 'CONSUMABLES', 'LOGISTICS', 'CAMP', 'SUBCONTRACTOR', 'OVERHEAD', name='cost_category', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_contract_rate_cards_organization_id'), table_name='contract_rate_cards')
    op.drop_index(op.f('ix_contract_rate_cards_contract_id'), table_name='contract_rate_cards')
    op.alter_column('contract_rate_cards', 'rate_type',
               existing_type=sa.Enum('DRILLING_METER', 'STANDBY_HOURLY', 'MOBILIZATION_FLAT', 'DEMOBILIZATION_FLAT', 'DAYWORK_HOURLY', name='rate_type', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_commercial_opportunities_organization_id'), table_name='commercial_opportunities')
    op.drop_index(op.f('ix_commercial_opportunities_client_id'), table_name='commercial_opportunities')
    op.drop_index(op.f('ix_commercial_opportunities_archived_at'), table_name='commercial_opportunities')
    op.alter_column('commercial_opportunities', 'tender_stage',
               existing_type=sa.Enum('PROSPECT', 'QUALIFIED', 'PROPOSAL_SENT', 'NEGOTIATION', 'WON', 'LOST', name='tender_stage', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'PROSPECT'::character varying"))
    op.drop_index(op.f('ix_client_published_artifacts_project_id'), table_name='client_published_artifacts')
    op.drop_index(op.f('ix_client_published_artifacts_organization_id'), table_name='client_published_artifacts')
    op.drop_index(op.f('ix_client_published_artifacts_client_id'), table_name='client_published_artifacts')
    op.alter_column('client_published_artifacts', 'artifact_type',
               existing_type=sa.Enum('SHIFT_REPORT', 'HOLE_LOG', 'PROGRESS_SUMMARY', 'PHOTO', 'INVOICE_STATEMENT', name='client_artifact_type', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_client_project_grants_project_id'), table_name='client_project_grants')
    op.drop_index(op.f('ix_client_project_grants_organization_id'), table_name='client_project_grants')
    op.drop_index(op.f('ix_client_project_grants_client_id'), table_name='client_project_grants')
    op.drop_index(op.f('ix_breakdown_job_cards_archived_at'), table_name='breakdown_job_cards')
    op.drop_index(op.f('ix_assistant_chat_messages_organization_id'), table_name='assistant_chat_messages')
    op.create_index(op.f('ix_assets_primary_operator'), 'assets', ['primary_operator_id'], unique=False)
    op.drop_index(op.f('ix_asset_log_files_organization_id'), table_name='asset_log_files')
    op.drop_constraint(op.f('fk_asset_fuel_reductions_fuel_log_id_asset_fuel_logs'), 'asset_fuel_reductions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_asset_fuel_reductions_fuel_log_id'), 'asset_fuel_reductions', 'asset_fuel_logs', ['fuel_log_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_asset_fuel_reductions_organization_id'), table_name='asset_fuel_reductions')
    op.drop_index(op.f('ix_action_trackers_organization_id'), table_name='action_trackers')
    op.drop_index(op.f('ix_action_trackers_archived_at'), table_name='action_trackers')
    # ### end Alembic commands ###
