const test=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const path=require('node:path');const ts=require('typescript');
function setup(fetcher){const storage=()=>{const map=new Map();return {getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)}};const localStorage=storage(),sessionStorage=storage();const events=[];const globals={localStorage,sessionStorage,window:{dispatchEvent:e=>events.push(e.type)},navigator:{},fetch:fetcher,Response,Headers,FormData,Event,console,Promise};const cache={};function load(file){if(cache[file])return cache[file];const source=fs.readFileSync(path.join(__dirname,'../src/lib',file+'.ts'),'utf8');const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;const exports={};vm.runInNewContext(code,{...globals,exports,require:n=>load(n.replace('./',''))});return cache[file]=exports;}return {api:load('api'),session:load('session'),localStorage,sessionStorage,events};}
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json'}});
test('login includes organization and invalid credentials never trigger refresh',async()=>{const requests=[];const {api}=setup(async(url,options)=>{requests.push({url,options});return json({error:{message:'Invalid credentials'}},401)});await assert.rejects(api.login({organization_id:'org-a',email:'a@example.com',password:'wrong'}),/Invalid credentials/);assert.equal(requests.length,1);assert.equal(JSON.parse(requests[0].options.body).organization_id,'org-a');});
test('parallel expired requests rotate refresh token once and retry',async()=>{let refreshes=0;const {api,session}=setup(async(url,options)=>{if(url.endsWith('/refresh')){refreshes++;await new Promise(r=>setTimeout(r,20));return json({access_token:'fresh',refresh_token:'rotated'});}return options.headers.get('Authorization')==='Bearer fresh'?json({ok:true}):json({},401);});session.setTokens('expired','refresh',true);const results=await Promise.all(Array.from({length:6},()=>api.apiFetch('/api/v1/auth/me')));assert.equal(refreshes,1);assert.ok(results.every(r=>r.ok));assert.equal(session.getRefreshToken(),'rotated');});
test('transient refresh failure preserves persisted session',async()=>{const {api,session}=setup(async url=>url.endsWith('/refresh')?json({},503):json({},401));session.setTokens('expired','keep-me',true);await assert.rejects(api.apiFetch('/api/v1/auth/me'),/retry/);assert.equal(session.getRefreshToken(),'keep-me');});
test('session and remembered login use the selected storage',()=>{const {session,localStorage,sessionStorage}=setup(()=>{});session.setTokens('a','r',true);assert.equal(localStorage.getItem('cestos_refresh_token'),'r');session.setTokens('b','s',false);assert.equal(localStorage.getItem('cestos_refresh_token'),null);assert.equal(sessionStorage.getItem('cestos_access_token'),'b');});
test('logout sends refresh token and clears both tokens',async()=>{let body;const {api,session}=setup(async(url,options)=>{body=JSON.parse(options.body);return new Response(null,{status:204});});session.setTokens('a','refresh',true);await api.logout();assert.equal(body.refresh_token,'refresh');assert.equal(session.getAccessToken(),null);});
test('204 after retry is accepted and rejected refresh ends session',async()=>{let fail=false;const {api,session,events}=setup(async(url,options)=>url.endsWith('/refresh')?(fail?json({},401):json({access_token:'fresh',refresh_token:'r2'})):options.headers.get('Authorization')==='Bearer fresh'?new Response(null,{status:204}):json({},401));session.setTokens('old','r1',true);assert.equal(await api.apiFetch('/api/v1/record',{method:'POST'}),undefined);fail=true;session.setTokens('expired','r3',true);await assert.rejects(api.apiFetch('/api/v1/record'));assert.equal(session.getRefreshToken(),null);assert.ok(events.includes('cestos:session-expired'));});
