 'use client';
import {useEffect,useState,ReactNode} from 'react';
import {RefreshCw,AlertCircle,X,Package} from 'lucide-react';
import {apiFetch} from '@/lib/api';
export type Row=Record<string,any>;
export const title=(value:string)=>value.replace(/_id$/, '').replace(/[_-]/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
export const rows=(data:any):Row[]=>Array.isArray(data)?data:Array.isArray(data?.items)?data.items:[];
export function display(value:any):string {if(value===null||value===undefined)return '—';if(typeof value==='boolean')return value?'Yes':'No';if(typeof value==='object')return value.name||value.full_name||[value.first_name,value.last_name].filter(Boolean).join(' ')||value.document_number||'—';if(typeof value==='string'&&/^\d{4}-\d{2}-\d{2}T/.test(value))return new Date(value).toLocaleString();return String(value);}
export function useData<T=any>(path:string|null){const [data,setData]=useState<T|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(!!path);const [version,setVersion]=useState(0);useEffect(()=>{let active=true;setData(null);setError('');if(!path){setLoading(false);return;}setLoading(true);apiFetch<T>(path).then(d=>{if(active)setData(d);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[path,version]);return{data,error,loading,reload:()=>setVersion(v=>v+1)};}
export function State({loading,error,retry,children}:{loading:boolean;error:string;retry:()=>void;children:ReactNode}){if(loading)return <div role="status" className="card p-8 text-muted-foreground animate-pulse">Loading live records…</div>;if(error)return <div role="alert" className="card border-red-200 p-6"><div className="flex gap-2 text-red-700"><AlertCircle size={18}/>{error}</div><button className="btn-secondary mt-4" onClick={retry}><RefreshCw size={14}/>Retry</button></div>;return <>{children}</>;}
export function Table({data,onSelect,columns}:{data:Row[];onSelect?:(row:Row)=>void;columns?:string[]}){const preferred=['name','item_name','store_name','first_name','last_name','employee_number','asset_number','item_number','document_number','transaction_number','transaction_type','status','employment_status','quantity_on_hand','quantity_available','normalized_quantity','quantity','reorder_status','start_date','end_date','expiry_date','created_at'];const keys=columns||preferred.filter(k=>data.some(r=>r[k]!=null)).slice(0,7);const actual=keys.length?keys:Object.keys(data[0]||{}).filter(k=>!k.endsWith('_id')&&k!=='id'&&typeof data[0][k]!=='object').slice(0,6);if(!data.length)return <div className="p-10 text-center text-muted-foreground"><Package className="mx-auto mb-3 opacity-40" size={28}/><p className="font-semibold text-foreground">No records to show</p><p className="text-sm mt-1">Records will appear here as your team works.</p></div>;return <div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead className="bg-muted text-muted-foreground text-xs uppercase"><tr>{actual.map(k=><th className="px-4 py-3 font-semibold whitespace-nowrap" key={k}>{title(k)}</th>)}{onSelect&&<th className="px-4 py-3">Details</th>}</tr></thead><tbody>{data.map((row,index)=><tr className="border-t border-border hover:bg-muted/50" key={row.id||index}>{actual.map(k=><td className="px-4 py-3 max-w-xs" key={k}>{k.includes('status')?<span className="rounded bg-secondary px-2 py-1 text-xs font-semibold text-primary">{display(row[k]).replace(/_/g,' ')}</span>:display(row[k])}</td>)}{onSelect&&<td className="px-4 py-3"><button className="text-primary font-semibold hover:underline" onClick={()=>onSelect(row)}>Open<span className="sr-only"> {display(row.name||row.document_number||row.employee_number||row.asset_number)}</span></button></td>}</tr>)}</tbody></table></div>;}
export function Modal({name,onClose,children}:{name:string;onClose:()=>void;children:ReactNode}){useEffect(()=>{const listener=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener);},[onClose]);return <div className="fixed inset-0 z-50 bg-slate-950/40 flex items-center justify-center p-3" onClick={e=>{if(e.target===e.currentTarget)onClose();}}><section role="dialog" aria-modal="true" aria-label={name} className="card shadow-xl w-full max-w-4xl max-h-[90vh] flex flex-col"><header className="flex justify-between items-center p-5 border-b"><h2 className="text-lg font-bold">{name}</h2><button autoFocus aria-label="Close dialog" onClick={onClose}><X size={20}/></button></header><div className="p-5 overflow-y-auto">{children}</div></section></div>;}
export function Facts({data}:{data:Row}){return <dl className="grid grid-cols-1 sm:grid-cols-2 gap-x-8 gap-y-4">{Object.entries(data).filter(([k,v])=>v!=null&&k!=='id'&&!k.endsWith('_id')&&!Array.isArray(v)&&!(typeof v==='object'&&!v.name)).map(([k,v])=><div key={k}><dt className="text-xs text-muted-foreground mb-1">{title(k)}</dt><dd className="text-sm break-words">{display(v)}</dd></div>)}</dl>;}
