 'use client';
import {useEffect,useState,FormEvent} from 'react';import {Eye,EyeOff,LogIn,Loader2} from 'lucide-react';import {useRouter} from 'next/navigation';
import {login,setTokens,apiFetch} from '@/lib/api';import {useAuth} from '@/components/AuthProvider';import AppLogo from '@/components/ui/AppLogo';
export default function LoginForm(){
 const router=useRouter();const auth=useAuth();const [org,setOrg]=useState(process.env.NEXT_PUBLIC_ORGANIZATION_ID||'');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [remember,setRemember]=useState(true);const [show,setShow]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [token,setToken]=useState('');
 useEffect(()=>{const reset=new URLSearchParams(window.location.hash.slice(1)).get('reset');if(reset){setToken(reset);window.history.replaceState(null,'',window.location.pathname);} const saved=localStorage.getItem('cestos_organization');if(saved)setOrg(saved);},[]);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{
  if(token){if(password!==confirm)throw new Error('Passwords do not match.');await apiFetch('/api/v1/hr/password-reset',{method:'POST',body:JSON.stringify({token,password})},false);setToken('');setPassword('');setConfirm('');setMessage('Password saved. Sign in with your new password.');}
  else {const data=await login({organization_id:org,email:email.trim(),password});setTokens(data.access_token,data.refresh_token,remember);localStorage.setItem('cestos_organization',org);await auth.reload();router.replace('/');}
 }catch(e){setError(e instanceof Error?e.message:'Unable to sign in.');}finally{setBusy(false);}}
 return <div className="flex-1 flex flex-col items-center justify-center px-6 py-12 bg-background overflow-y-auto"><div className="w-full max-w-md"><div className="lg:hidden flex items-center gap-2 mb-8"><AppLogo size={32}/><span className="font-bold text-lg">Cestos Operations</span></div><span className="text-xs font-semibold text-primary uppercase tracking-widest">Your operations workspace</span><h2 className="text-2xl font-bold mt-3">{token?'Set your password':'Welcome back'}</h2><p className="text-sm text-muted-foreground mt-2 mb-8">{token?'Choose a password with at least 12 characters.':'Sign in with the account provided by your administrator.'}</p>
 {error&&<p role="alert" className="mb-5 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}{message&&<p role="status" className="mb-5 rounded bg-secondary p-3 text-sm text-primary">{message}</p>}
 <form onSubmit={submit} className="space-y-5">{!token&&<><label className="block text-sm font-semibold">Organization ID<input className="input-field mt-2 font-mono text-xs" value={org} onChange={e=>setOrg(e.target.value)} required pattern="[0-9a-fA-F-]{36}" autoComplete="organization"/></label><label className="block text-sm font-semibold">Work email<input className="input-field mt-2" value={email} onChange={e=>setEmail(e.target.value)} type="email" autoComplete="username" required/></label></>}
 <label className="block text-sm font-semibold">{token?'New password':'Password'}<div className="relative mt-2"><input className="input-field pr-10" value={password} onChange={e=>setPassword(e.target.value)} type={show?'text':'password'} autoComplete={token?'new-password':'current-password'} required minLength={token?12:1} maxLength={128}/><button type="button" className="absolute right-3 top-3 text-muted-foreground" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}>{show?<EyeOff size={16}/>:<Eye size={16}/>}</button></div></label>
 {token?<label className="block text-sm font-semibold">Confirm password<input className="input-field mt-2" type="password" autoComplete="new-password" required value={confirm} onChange={e=>setConfirm(e.target.value)}/></label>:<div className="flex items-center justify-between gap-2 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/>Keep me signed in</label><button type="button" className="text-primary" onClick={()=>setMessage('Ask your administrator to send a password reset email from your employee account.')}>Forgot password?</button></div>}
 <button disabled={busy} className="btn-primary w-full justify-center py-3">{busy?<Loader2 size={16} className="animate-spin"/>:<LogIn size={16}/>} {busy?'Please wait…':token?'Save password':'Sign in'}</button></form><p className="text-xs text-muted-foreground mt-6">Access and available actions follow your organization’s permissions.</p></div></div>;
}
